// Code generated by tools/wl_gen.py. DO NOT EDIT.
//
// Sources:
//   /usr/share/wayland/wayland.xml
//   /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml
//   /usr/share/wayland-protocols/unstable/xdg-decoration/xdg-decoration-unstable-v1.xml
//   /usr/share/wayland-protocols/staging/ext-background-effect/ext-background-effect-v1.xml
package wayland

import "core:c"

wl_display :: struct {}
wl_registry :: struct {}
wl_callback :: struct {}
wl_compositor :: struct {}
wl_shm_pool :: struct {}
wl_shm :: struct {}
wl_buffer :: struct {}
wl_data_offer :: struct {}
wl_data_source :: struct {}
wl_data_device :: struct {}
wl_data_device_manager :: struct {}
wl_shell :: struct {}
wl_shell_surface :: struct {}
wl_surface :: struct {}
wl_seat :: struct {}
wl_pointer :: struct {}
wl_keyboard :: struct {}
wl_touch :: struct {}
wl_output :: struct {}
wl_region :: struct {}
wl_subcompositor :: struct {}
wl_subsurface :: struct {}
wl_fixes :: struct {}
xdg_wm_base :: struct {}
xdg_positioner :: struct {}
xdg_surface :: struct {}
xdg_toplevel :: struct {}
xdg_popup :: struct {}
zxdg_decoration_manager_v1 :: struct {}
zxdg_toplevel_decoration_v1 :: struct {}
ext_background_effect_manager_v1 :: struct {}
ext_background_effect_surface_v1 :: struct {}

wl_display_interface: Interface
wl_registry_interface: Interface
wl_callback_interface: Interface
wl_compositor_interface: Interface
wl_shm_pool_interface: Interface
wl_shm_interface: Interface
wl_buffer_interface: Interface
wl_data_offer_interface: Interface
wl_data_source_interface: Interface
wl_data_device_interface: Interface
wl_data_device_manager_interface: Interface
wl_shell_interface: Interface
wl_shell_surface_interface: Interface
wl_surface_interface: Interface
wl_seat_interface: Interface
wl_pointer_interface: Interface
wl_keyboard_interface: Interface
wl_touch_interface: Interface
wl_output_interface: Interface
wl_region_interface: Interface
wl_subcompositor_interface: Interface
wl_subsurface_interface: Interface
wl_fixes_interface: Interface
xdg_wm_base_interface: Interface
xdg_positioner_interface: Interface
xdg_surface_interface: Interface
xdg_toplevel_interface: Interface
xdg_popup_interface: Interface
zxdg_decoration_manager_v1_interface: Interface
zxdg_toplevel_decoration_v1_interface: Interface
ext_background_effect_manager_v1_interface: Interface
ext_background_effect_surface_v1_interface: Interface

@(private) wl_display_requests: [2]Message
@(private) wl_display_requests_types_0 := [1]^Interface{&wl_callback_interface}
@(private) wl_display_requests_types_1 := [1]^Interface{&wl_registry_interface}
@(private) wl_display_events: [2]Message
@(private) wl_display_events_types_0 := [3]^Interface{nil, nil, nil}
@(private) wl_display_events_types_1 := [1]^Interface{nil}
@(private) wl_registry_requests: [1]Message
@(private) wl_registry_requests_types_0 := [4]^Interface{nil, nil, nil, nil}
@(private) wl_registry_events: [2]Message
@(private) wl_registry_events_types_0 := [3]^Interface{nil, nil, nil}
@(private) wl_registry_events_types_1 := [1]^Interface{nil}
@(private) wl_callback_events: [1]Message
@(private) wl_callback_events_types_0 := [1]^Interface{nil}
@(private) wl_compositor_requests: [3]Message
@(private) wl_compositor_requests_types_0 := [1]^Interface{&wl_surface_interface}
@(private) wl_compositor_requests_types_1 := [1]^Interface{&wl_region_interface}
@(private) wl_shm_pool_requests: [3]Message
@(private) wl_shm_pool_requests_types_0 := [6]^Interface{&wl_buffer_interface, nil, nil, nil, nil, nil}
@(private) wl_shm_pool_requests_types_2 := [1]^Interface{nil}
@(private) wl_shm_requests: [2]Message
@(private) wl_shm_requests_types_0 := [3]^Interface{&wl_shm_pool_interface, nil, nil}
@(private) wl_shm_events: [1]Message
@(private) wl_shm_events_types_0 := [1]^Interface{nil}
@(private) wl_buffer_requests: [1]Message
@(private) wl_buffer_events: [1]Message
@(private) wl_data_offer_requests: [5]Message
@(private) wl_data_offer_requests_types_0 := [2]^Interface{nil, nil}
@(private) wl_data_offer_requests_types_1 := [2]^Interface{nil, nil}
@(private) wl_data_offer_requests_types_4 := [2]^Interface{nil, nil}
@(private) wl_data_offer_events: [3]Message
@(private) wl_data_offer_events_types_0 := [1]^Interface{nil}
@(private) wl_data_offer_events_types_1 := [1]^Interface{nil}
@(private) wl_data_offer_events_types_2 := [1]^Interface{nil}
@(private) wl_data_source_requests: [3]Message
@(private) wl_data_source_requests_types_0 := [1]^Interface{nil}
@(private) wl_data_source_requests_types_2 := [1]^Interface{nil}
@(private) wl_data_source_events: [6]Message
@(private) wl_data_source_events_types_0 := [1]^Interface{nil}
@(private) wl_data_source_events_types_1 := [2]^Interface{nil, nil}
@(private) wl_data_source_events_types_5 := [1]^Interface{nil}
@(private) wl_data_device_requests: [3]Message
@(private) wl_data_device_requests_types_0 := [4]^Interface{&wl_data_source_interface, &wl_surface_interface, &wl_surface_interface, nil}
@(private) wl_data_device_requests_types_1 := [2]^Interface{&wl_data_source_interface, nil}
@(private) wl_data_device_events: [6]Message
@(private) wl_data_device_events_types_0 := [1]^Interface{&wl_data_offer_interface}
@(private) wl_data_device_events_types_1 := [5]^Interface{nil, &wl_surface_interface, nil, nil, &wl_data_offer_interface}
@(private) wl_data_device_events_types_3 := [3]^Interface{nil, nil, nil}
@(private) wl_data_device_events_types_5 := [1]^Interface{&wl_data_offer_interface}
@(private) wl_data_device_manager_requests: [3]Message
@(private) wl_data_device_manager_requests_types_0 := [1]^Interface{&wl_data_source_interface}
@(private) wl_data_device_manager_requests_types_1 := [2]^Interface{&wl_data_device_interface, &wl_seat_interface}
@(private) wl_shell_requests: [1]Message
@(private) wl_shell_requests_types_0 := [2]^Interface{&wl_shell_surface_interface, &wl_surface_interface}
@(private) wl_shell_surface_requests: [10]Message
@(private) wl_shell_surface_requests_types_0 := [1]^Interface{nil}
@(private) wl_shell_surface_requests_types_1 := [2]^Interface{&wl_seat_interface, nil}
@(private) wl_shell_surface_requests_types_2 := [3]^Interface{&wl_seat_interface, nil, nil}
@(private) wl_shell_surface_requests_types_4 := [4]^Interface{&wl_surface_interface, nil, nil, nil}
@(private) wl_shell_surface_requests_types_5 := [3]^Interface{nil, nil, &wl_output_interface}
@(private) wl_shell_surface_requests_types_6 := [6]^Interface{&wl_seat_interface, nil, &wl_surface_interface, nil, nil, nil}
@(private) wl_shell_surface_requests_types_7 := [1]^Interface{&wl_output_interface}
@(private) wl_shell_surface_requests_types_8 := [1]^Interface{nil}
@(private) wl_shell_surface_requests_types_9 := [1]^Interface{nil}
@(private) wl_shell_surface_events: [3]Message
@(private) wl_shell_surface_events_types_0 := [1]^Interface{nil}
@(private) wl_shell_surface_events_types_1 := [3]^Interface{nil, nil, nil}
@(private) wl_surface_requests: [12]Message
@(private) wl_surface_requests_types_1 := [3]^Interface{&wl_buffer_interface, nil, nil}
@(private) wl_surface_requests_types_2 := [4]^Interface{nil, nil, nil, nil}
@(private) wl_surface_requests_types_3 := [1]^Interface{&wl_callback_interface}
@(private) wl_surface_requests_types_4 := [1]^Interface{&wl_region_interface}
@(private) wl_surface_requests_types_5 := [1]^Interface{&wl_region_interface}
@(private) wl_surface_requests_types_7 := [1]^Interface{nil}
@(private) wl_surface_requests_types_8 := [1]^Interface{nil}
@(private) wl_surface_requests_types_9 := [4]^Interface{nil, nil, nil, nil}
@(private) wl_surface_requests_types_10 := [2]^Interface{nil, nil}
@(private) wl_surface_requests_types_11 := [1]^Interface{&wl_callback_interface}
@(private) wl_surface_events: [4]Message
@(private) wl_surface_events_types_0 := [1]^Interface{&wl_output_interface}
@(private) wl_surface_events_types_1 := [1]^Interface{&wl_output_interface}
@(private) wl_surface_events_types_2 := [1]^Interface{nil}
@(private) wl_surface_events_types_3 := [1]^Interface{nil}
@(private) wl_seat_requests: [4]Message
@(private) wl_seat_requests_types_0 := [1]^Interface{&wl_pointer_interface}
@(private) wl_seat_requests_types_1 := [1]^Interface{&wl_keyboard_interface}
@(private) wl_seat_requests_types_2 := [1]^Interface{&wl_touch_interface}
@(private) wl_seat_events: [2]Message
@(private) wl_seat_events_types_0 := [1]^Interface{nil}
@(private) wl_seat_events_types_1 := [1]^Interface{nil}
@(private) wl_pointer_requests: [2]Message
@(private) wl_pointer_requests_types_0 := [4]^Interface{nil, &wl_surface_interface, nil, nil}
@(private) wl_pointer_events: [12]Message
@(private) wl_pointer_events_types_0 := [4]^Interface{nil, &wl_surface_interface, nil, nil}
@(private) wl_pointer_events_types_1 := [2]^Interface{nil, &wl_surface_interface}
@(private) wl_pointer_events_types_2 := [3]^Interface{nil, nil, nil}
@(private) wl_pointer_events_types_3 := [4]^Interface{nil, nil, nil, nil}
@(private) wl_pointer_events_types_4 := [3]^Interface{nil, nil, nil}
@(private) wl_pointer_events_types_6 := [1]^Interface{nil}
@(private) wl_pointer_events_types_7 := [2]^Interface{nil, nil}
@(private) wl_pointer_events_types_8 := [2]^Interface{nil, nil}
@(private) wl_pointer_events_types_9 := [2]^Interface{nil, nil}
@(private) wl_pointer_events_types_10 := [2]^Interface{nil, nil}
@(private) wl_pointer_events_types_11 := [2]^Interface{nil, nil}
@(private) wl_keyboard_requests: [1]Message
@(private) wl_keyboard_events: [6]Message
@(private) wl_keyboard_events_types_0 := [3]^Interface{nil, nil, nil}
@(private) wl_keyboard_events_types_1 := [3]^Interface{nil, &wl_surface_interface, nil}
@(private) wl_keyboard_events_types_2 := [2]^Interface{nil, &wl_surface_interface}
@(private) wl_keyboard_events_types_3 := [4]^Interface{nil, nil, nil, nil}
@(private) wl_keyboard_events_types_4 := [5]^Interface{nil, nil, nil, nil, nil}
@(private) wl_keyboard_events_types_5 := [2]^Interface{nil, nil}
@(private) wl_touch_requests: [1]Message
@(private) wl_touch_events: [7]Message
@(private) wl_touch_events_types_0 := [6]^Interface{nil, nil, &wl_surface_interface, nil, nil, nil}
@(private) wl_touch_events_types_1 := [3]^Interface{nil, nil, nil}
@(private) wl_touch_events_types_2 := [4]^Interface{nil, nil, nil, nil}
@(private) wl_touch_events_types_5 := [3]^Interface{nil, nil, nil}
@(private) wl_touch_events_types_6 := [2]^Interface{nil, nil}
@(private) wl_output_requests: [1]Message
@(private) wl_output_events: [6]Message
@(private) wl_output_events_types_0 := [8]^Interface{nil, nil, nil, nil, nil, nil, nil, nil}
@(private) wl_output_events_types_1 := [4]^Interface{nil, nil, nil, nil}
@(private) wl_output_events_types_3 := [1]^Interface{nil}
@(private) wl_output_events_types_4 := [1]^Interface{nil}
@(private) wl_output_events_types_5 := [1]^Interface{nil}
@(private) wl_region_requests: [3]Message
@(private) wl_region_requests_types_1 := [4]^Interface{nil, nil, nil, nil}
@(private) wl_region_requests_types_2 := [4]^Interface{nil, nil, nil, nil}
@(private) wl_subcompositor_requests: [2]Message
@(private) wl_subcompositor_requests_types_1 := [3]^Interface{&wl_subsurface_interface, &wl_surface_interface, &wl_surface_interface}
@(private) wl_subsurface_requests: [6]Message
@(private) wl_subsurface_requests_types_1 := [2]^Interface{nil, nil}
@(private) wl_subsurface_requests_types_2 := [1]^Interface{&wl_surface_interface}
@(private) wl_subsurface_requests_types_3 := [1]^Interface{&wl_surface_interface}
@(private) wl_fixes_requests: [3]Message
@(private) wl_fixes_requests_types_1 := [1]^Interface{&wl_registry_interface}
@(private) wl_fixes_requests_types_2 := [2]^Interface{&wl_registry_interface, nil}
@(private) xdg_wm_base_requests: [4]Message
@(private) xdg_wm_base_requests_types_1 := [1]^Interface{&xdg_positioner_interface}
@(private) xdg_wm_base_requests_types_2 := [2]^Interface{&xdg_surface_interface, &wl_surface_interface}
@(private) xdg_wm_base_requests_types_3 := [1]^Interface{nil}
@(private) xdg_wm_base_events: [1]Message
@(private) xdg_wm_base_events_types_0 := [1]^Interface{nil}
@(private) xdg_positioner_requests: [10]Message
@(private) xdg_positioner_requests_types_1 := [2]^Interface{nil, nil}
@(private) xdg_positioner_requests_types_2 := [4]^Interface{nil, nil, nil, nil}
@(private) xdg_positioner_requests_types_3 := [1]^Interface{nil}
@(private) xdg_positioner_requests_types_4 := [1]^Interface{nil}
@(private) xdg_positioner_requests_types_5 := [1]^Interface{nil}
@(private) xdg_positioner_requests_types_6 := [2]^Interface{nil, nil}
@(private) xdg_positioner_requests_types_8 := [2]^Interface{nil, nil}
@(private) xdg_positioner_requests_types_9 := [1]^Interface{nil}
@(private) xdg_surface_requests: [5]Message
@(private) xdg_surface_requests_types_1 := [1]^Interface{&xdg_toplevel_interface}
@(private) xdg_surface_requests_types_2 := [3]^Interface{&xdg_popup_interface, &xdg_surface_interface, &xdg_positioner_interface}
@(private) xdg_surface_requests_types_3 := [4]^Interface{nil, nil, nil, nil}
@(private) xdg_surface_requests_types_4 := [1]^Interface{nil}
@(private) xdg_surface_events: [1]Message
@(private) xdg_surface_events_types_0 := [1]^Interface{nil}
@(private) xdg_toplevel_requests: [14]Message
@(private) xdg_toplevel_requests_types_1 := [1]^Interface{&xdg_toplevel_interface}
@(private) xdg_toplevel_requests_types_2 := [1]^Interface{nil}
@(private) xdg_toplevel_requests_types_3 := [1]^Interface{nil}
@(private) xdg_toplevel_requests_types_4 := [4]^Interface{&wl_seat_interface, nil, nil, nil}
@(private) xdg_toplevel_requests_types_5 := [2]^Interface{&wl_seat_interface, nil}
@(private) xdg_toplevel_requests_types_6 := [3]^Interface{&wl_seat_interface, nil, nil}
@(private) xdg_toplevel_requests_types_7 := [2]^Interface{nil, nil}
@(private) xdg_toplevel_requests_types_8 := [2]^Interface{nil, nil}
@(private) xdg_toplevel_requests_types_11 := [1]^Interface{&wl_output_interface}
@(private) xdg_toplevel_events: [4]Message
@(private) xdg_toplevel_events_types_0 := [3]^Interface{nil, nil, nil}
@(private) xdg_toplevel_events_types_2 := [2]^Interface{nil, nil}
@(private) xdg_toplevel_events_types_3 := [1]^Interface{nil}
@(private) xdg_popup_requests: [3]Message
@(private) xdg_popup_requests_types_1 := [2]^Interface{&wl_seat_interface, nil}
@(private) xdg_popup_requests_types_2 := [2]^Interface{&xdg_positioner_interface, nil}
@(private) xdg_popup_events: [3]Message
@(private) xdg_popup_events_types_0 := [4]^Interface{nil, nil, nil, nil}
@(private) xdg_popup_events_types_2 := [1]^Interface{nil}
@(private) zxdg_decoration_manager_v1_requests: [2]Message
@(private) zxdg_decoration_manager_v1_requests_types_1 := [2]^Interface{&zxdg_toplevel_decoration_v1_interface, &xdg_toplevel_interface}
@(private) zxdg_toplevel_decoration_v1_requests: [3]Message
@(private) zxdg_toplevel_decoration_v1_requests_types_1 := [1]^Interface{nil}
@(private) zxdg_toplevel_decoration_v1_events: [1]Message
@(private) zxdg_toplevel_decoration_v1_events_types_0 := [1]^Interface{nil}
@(private) ext_background_effect_manager_v1_requests: [2]Message
@(private) ext_background_effect_manager_v1_requests_types_1 := [2]^Interface{&ext_background_effect_surface_v1_interface, &wl_surface_interface}
@(private) ext_background_effect_manager_v1_events: [1]Message
@(private) ext_background_effect_manager_v1_events_types_0 := [1]^Interface{nil}
@(private) ext_background_effect_surface_v1_requests: [2]Message
@(private) ext_background_effect_surface_v1_requests_types_1 := [1]^Interface{&wl_region_interface}

@(init, private)
init_interfaces :: proc "contextless" () {
	wl_display_requests[0] = {"sync", "n", &wl_display_requests_types_0[0]}
	wl_display_requests[1] = {"get_registry", "n", &wl_display_requests_types_1[0]}
	wl_display_events[0] = {"error", "ous", &wl_display_events_types_0[0]}
	wl_display_events[1] = {"delete_id", "u", &wl_display_events_types_1[0]}
	wl_display_interface = {"wl_display", 1, 2, &wl_display_requests[0], 2, &wl_display_events[0]}
	wl_registry_requests[0] = {"bind", "usun", &wl_registry_requests_types_0[0]}
	wl_registry_events[0] = {"global", "usu", &wl_registry_events_types_0[0]}
	wl_registry_events[1] = {"global_remove", "u", &wl_registry_events_types_1[0]}
	wl_registry_interface = {"wl_registry", 1, 1, &wl_registry_requests[0], 2, &wl_registry_events[0]}
	wl_callback_events[0] = {"done", "u", &wl_callback_events_types_0[0]}
	wl_callback_interface = {"wl_callback", 1, 0, nil, 1, &wl_callback_events[0]}
	wl_compositor_requests[0] = {"create_surface", "n", &wl_compositor_requests_types_0[0]}
	wl_compositor_requests[1] = {"create_region", "n", &wl_compositor_requests_types_1[0]}
	wl_compositor_requests[2] = {"release", "7", nil}
	wl_compositor_interface = {"wl_compositor", 7, 3, &wl_compositor_requests[0], 0, nil}
	wl_shm_pool_requests[0] = {"create_buffer", "niiiiu", &wl_shm_pool_requests_types_0[0]}
	wl_shm_pool_requests[1] = {"destroy", "", nil}
	wl_shm_pool_requests[2] = {"resize", "i", &wl_shm_pool_requests_types_2[0]}
	wl_shm_pool_interface = {"wl_shm_pool", 3, 3, &wl_shm_pool_requests[0], 0, nil}
	wl_shm_requests[0] = {"create_pool", "nhi", &wl_shm_requests_types_0[0]}
	wl_shm_requests[1] = {"release", "2", nil}
	wl_shm_events[0] = {"format", "u", &wl_shm_events_types_0[0]}
	wl_shm_interface = {"wl_shm", 3, 2, &wl_shm_requests[0], 1, &wl_shm_events[0]}
	wl_buffer_requests[0] = {"destroy", "", nil}
	wl_buffer_events[0] = {"release", "", nil}
	wl_buffer_interface = {"wl_buffer", 1, 1, &wl_buffer_requests[0], 1, &wl_buffer_events[0]}
	wl_data_offer_requests[0] = {"accept", "u?s", &wl_data_offer_requests_types_0[0]}
	wl_data_offer_requests[1] = {"receive", "sh", &wl_data_offer_requests_types_1[0]}
	wl_data_offer_requests[2] = {"destroy", "", nil}
	wl_data_offer_requests[3] = {"finish", "3", nil}
	wl_data_offer_requests[4] = {"set_actions", "3uu", &wl_data_offer_requests_types_4[0]}
	wl_data_offer_events[0] = {"offer", "s", &wl_data_offer_events_types_0[0]}
	wl_data_offer_events[1] = {"source_actions", "3u", &wl_data_offer_events_types_1[0]}
	wl_data_offer_events[2] = {"action", "3u", &wl_data_offer_events_types_2[0]}
	wl_data_offer_interface = {"wl_data_offer", 4, 5, &wl_data_offer_requests[0], 3, &wl_data_offer_events[0]}
	wl_data_source_requests[0] = {"offer", "s", &wl_data_source_requests_types_0[0]}
	wl_data_source_requests[1] = {"destroy", "", nil}
	wl_data_source_requests[2] = {"set_actions", "3u", &wl_data_source_requests_types_2[0]}
	wl_data_source_events[0] = {"target", "?s", &wl_data_source_events_types_0[0]}
	wl_data_source_events[1] = {"send", "sh", &wl_data_source_events_types_1[0]}
	wl_data_source_events[2] = {"cancelled", "", nil}
	wl_data_source_events[3] = {"dnd_drop_performed", "3", nil}
	wl_data_source_events[4] = {"dnd_finished", "3", nil}
	wl_data_source_events[5] = {"action", "3u", &wl_data_source_events_types_5[0]}
	wl_data_source_interface = {"wl_data_source", 4, 3, &wl_data_source_requests[0], 6, &wl_data_source_events[0]}
	wl_data_device_requests[0] = {"start_drag", "?oo?ou", &wl_data_device_requests_types_0[0]}
	wl_data_device_requests[1] = {"set_selection", "?ou", &wl_data_device_requests_types_1[0]}
	wl_data_device_requests[2] = {"release", "2", nil}
	wl_data_device_events[0] = {"data_offer", "n", &wl_data_device_events_types_0[0]}
	wl_data_device_events[1] = {"enter", "uoff?o", &wl_data_device_events_types_1[0]}
	wl_data_device_events[2] = {"leave", "", nil}
	wl_data_device_events[3] = {"motion", "uff", &wl_data_device_events_types_3[0]}
	wl_data_device_events[4] = {"drop", "", nil}
	wl_data_device_events[5] = {"selection", "?o", &wl_data_device_events_types_5[0]}
	wl_data_device_interface = {"wl_data_device", 4, 3, &wl_data_device_requests[0], 6, &wl_data_device_events[0]}
	wl_data_device_manager_requests[0] = {"create_data_source", "n", &wl_data_device_manager_requests_types_0[0]}
	wl_data_device_manager_requests[1] = {"get_data_device", "no", &wl_data_device_manager_requests_types_1[0]}
	wl_data_device_manager_requests[2] = {"release", "4", nil}
	wl_data_device_manager_interface = {"wl_data_device_manager", 4, 3, &wl_data_device_manager_requests[0], 0, nil}
	wl_shell_requests[0] = {"get_shell_surface", "no", &wl_shell_requests_types_0[0]}
	wl_shell_interface = {"wl_shell", 1, 1, &wl_shell_requests[0], 0, nil}
	wl_shell_surface_requests[0] = {"pong", "u", &wl_shell_surface_requests_types_0[0]}
	wl_shell_surface_requests[1] = {"move", "ou", &wl_shell_surface_requests_types_1[0]}
	wl_shell_surface_requests[2] = {"resize", "ouu", &wl_shell_surface_requests_types_2[0]}
	wl_shell_surface_requests[3] = {"set_toplevel", "", nil}
	wl_shell_surface_requests[4] = {"set_transient", "oiiu", &wl_shell_surface_requests_types_4[0]}
	wl_shell_surface_requests[5] = {"set_fullscreen", "uu?o", &wl_shell_surface_requests_types_5[0]}
	wl_shell_surface_requests[6] = {"set_popup", "ouoiiu", &wl_shell_surface_requests_types_6[0]}
	wl_shell_surface_requests[7] = {"set_maximized", "?o", &wl_shell_surface_requests_types_7[0]}
	wl_shell_surface_requests[8] = {"set_title", "s", &wl_shell_surface_requests_types_8[0]}
	wl_shell_surface_requests[9] = {"set_class", "s", &wl_shell_surface_requests_types_9[0]}
	wl_shell_surface_events[0] = {"ping", "u", &wl_shell_surface_events_types_0[0]}
	wl_shell_surface_events[1] = {"configure", "uii", &wl_shell_surface_events_types_1[0]}
	wl_shell_surface_events[2] = {"popup_done", "", nil}
	wl_shell_surface_interface = {"wl_shell_surface", 1, 10, &wl_shell_surface_requests[0], 3, &wl_shell_surface_events[0]}
	wl_surface_requests[0] = {"destroy", "", nil}
	wl_surface_requests[1] = {"attach", "?oii", &wl_surface_requests_types_1[0]}
	wl_surface_requests[2] = {"damage", "iiii", &wl_surface_requests_types_2[0]}
	wl_surface_requests[3] = {"frame", "n", &wl_surface_requests_types_3[0]}
	wl_surface_requests[4] = {"set_opaque_region", "?o", &wl_surface_requests_types_4[0]}
	wl_surface_requests[5] = {"set_input_region", "?o", &wl_surface_requests_types_5[0]}
	wl_surface_requests[6] = {"commit", "", nil}
	wl_surface_requests[7] = {"set_buffer_transform", "2i", &wl_surface_requests_types_7[0]}
	wl_surface_requests[8] = {"set_buffer_scale", "3i", &wl_surface_requests_types_8[0]}
	wl_surface_requests[9] = {"damage_buffer", "4iiii", &wl_surface_requests_types_9[0]}
	wl_surface_requests[10] = {"offset", "5ii", &wl_surface_requests_types_10[0]}
	wl_surface_requests[11] = {"get_release", "7n", &wl_surface_requests_types_11[0]}
	wl_surface_events[0] = {"enter", "o", &wl_surface_events_types_0[0]}
	wl_surface_events[1] = {"leave", "o", &wl_surface_events_types_1[0]}
	wl_surface_events[2] = {"preferred_buffer_scale", "6i", &wl_surface_events_types_2[0]}
	wl_surface_events[3] = {"preferred_buffer_transform", "6u", &wl_surface_events_types_3[0]}
	wl_surface_interface = {"wl_surface", 7, 12, &wl_surface_requests[0], 4, &wl_surface_events[0]}
	wl_seat_requests[0] = {"get_pointer", "n", &wl_seat_requests_types_0[0]}
	wl_seat_requests[1] = {"get_keyboard", "n", &wl_seat_requests_types_1[0]}
	wl_seat_requests[2] = {"get_touch", "n", &wl_seat_requests_types_2[0]}
	wl_seat_requests[3] = {"release", "5", nil}
	wl_seat_events[0] = {"capabilities", "u", &wl_seat_events_types_0[0]}
	wl_seat_events[1] = {"name", "2s", &wl_seat_events_types_1[0]}
	wl_seat_interface = {"wl_seat", 11, 4, &wl_seat_requests[0], 2, &wl_seat_events[0]}
	wl_pointer_requests[0] = {"set_cursor", "u?oii", &wl_pointer_requests_types_0[0]}
	wl_pointer_requests[1] = {"release", "3", nil}
	wl_pointer_events[0] = {"enter", "uoff", &wl_pointer_events_types_0[0]}
	wl_pointer_events[1] = {"leave", "uo", &wl_pointer_events_types_1[0]}
	wl_pointer_events[2] = {"motion", "uff", &wl_pointer_events_types_2[0]}
	wl_pointer_events[3] = {"button", "uuuu", &wl_pointer_events_types_3[0]}
	wl_pointer_events[4] = {"axis", "uuf", &wl_pointer_events_types_4[0]}
	wl_pointer_events[5] = {"frame", "5", nil}
	wl_pointer_events[6] = {"axis_source", "5u", &wl_pointer_events_types_6[0]}
	wl_pointer_events[7] = {"axis_stop", "5uu", &wl_pointer_events_types_7[0]}
	wl_pointer_events[8] = {"axis_discrete", "5ui", &wl_pointer_events_types_8[0]}
	wl_pointer_events[9] = {"axis_value120", "8ui", &wl_pointer_events_types_9[0]}
	wl_pointer_events[10] = {"axis_relative_direction", "9uu", &wl_pointer_events_types_10[0]}
	wl_pointer_events[11] = {"warp", "11ff", &wl_pointer_events_types_11[0]}
	wl_pointer_interface = {"wl_pointer", 11, 2, &wl_pointer_requests[0], 12, &wl_pointer_events[0]}
	wl_keyboard_requests[0] = {"release", "3", nil}
	wl_keyboard_events[0] = {"keymap", "uhu", &wl_keyboard_events_types_0[0]}
	wl_keyboard_events[1] = {"enter", "uoa", &wl_keyboard_events_types_1[0]}
	wl_keyboard_events[2] = {"leave", "uo", &wl_keyboard_events_types_2[0]}
	wl_keyboard_events[3] = {"key", "uuuu", &wl_keyboard_events_types_3[0]}
	wl_keyboard_events[4] = {"modifiers", "uuuuu", &wl_keyboard_events_types_4[0]}
	wl_keyboard_events[5] = {"repeat_info", "4ii", &wl_keyboard_events_types_5[0]}
	wl_keyboard_interface = {"wl_keyboard", 11, 1, &wl_keyboard_requests[0], 6, &wl_keyboard_events[0]}
	wl_touch_requests[0] = {"release", "3", nil}
	wl_touch_events[0] = {"down", "uuoiff", &wl_touch_events_types_0[0]}
	wl_touch_events[1] = {"up", "uui", &wl_touch_events_types_1[0]}
	wl_touch_events[2] = {"motion", "uiff", &wl_touch_events_types_2[0]}
	wl_touch_events[3] = {"frame", "", nil}
	wl_touch_events[4] = {"cancel", "", nil}
	wl_touch_events[5] = {"shape", "6iff", &wl_touch_events_types_5[0]}
	wl_touch_events[6] = {"orientation", "6if", &wl_touch_events_types_6[0]}
	wl_touch_interface = {"wl_touch", 11, 1, &wl_touch_requests[0], 7, &wl_touch_events[0]}
	wl_output_requests[0] = {"release", "3", nil}
	wl_output_events[0] = {"geometry", "iiiiissi", &wl_output_events_types_0[0]}
	wl_output_events[1] = {"mode", "uiii", &wl_output_events_types_1[0]}
	wl_output_events[2] = {"done", "2", nil}
	wl_output_events[3] = {"scale", "2i", &wl_output_events_types_3[0]}
	wl_output_events[4] = {"name", "4s", &wl_output_events_types_4[0]}
	wl_output_events[5] = {"description", "4s", &wl_output_events_types_5[0]}
	wl_output_interface = {"wl_output", 4, 1, &wl_output_requests[0], 6, &wl_output_events[0]}
	wl_region_requests[0] = {"destroy", "", nil}
	wl_region_requests[1] = {"add", "iiii", &wl_region_requests_types_1[0]}
	wl_region_requests[2] = {"subtract", "iiii", &wl_region_requests_types_2[0]}
	wl_region_interface = {"wl_region", 7, 3, &wl_region_requests[0], 0, nil}
	wl_subcompositor_requests[0] = {"destroy", "", nil}
	wl_subcompositor_requests[1] = {"get_subsurface", "noo", &wl_subcompositor_requests_types_1[0]}
	wl_subcompositor_interface = {"wl_subcompositor", 1, 2, &wl_subcompositor_requests[0], 0, nil}
	wl_subsurface_requests[0] = {"destroy", "", nil}
	wl_subsurface_requests[1] = {"set_position", "ii", &wl_subsurface_requests_types_1[0]}
	wl_subsurface_requests[2] = {"place_above", "o", &wl_subsurface_requests_types_2[0]}
	wl_subsurface_requests[3] = {"place_below", "o", &wl_subsurface_requests_types_3[0]}
	wl_subsurface_requests[4] = {"set_sync", "", nil}
	wl_subsurface_requests[5] = {"set_desync", "", nil}
	wl_subsurface_interface = {"wl_subsurface", 1, 6, &wl_subsurface_requests[0], 0, nil}
	wl_fixes_requests[0] = {"destroy", "", nil}
	wl_fixes_requests[1] = {"destroy_registry", "o", &wl_fixes_requests_types_1[0]}
	wl_fixes_requests[2] = {"ack_global_remove", "2ou", &wl_fixes_requests_types_2[0]}
	wl_fixes_interface = {"wl_fixes", 2, 3, &wl_fixes_requests[0], 0, nil}
	xdg_wm_base_requests[0] = {"destroy", "", nil}
	xdg_wm_base_requests[1] = {"create_positioner", "n", &xdg_wm_base_requests_types_1[0]}
	xdg_wm_base_requests[2] = {"get_xdg_surface", "no", &xdg_wm_base_requests_types_2[0]}
	xdg_wm_base_requests[3] = {"pong", "u", &xdg_wm_base_requests_types_3[0]}
	xdg_wm_base_events[0] = {"ping", "u", &xdg_wm_base_events_types_0[0]}
	xdg_wm_base_interface = {"xdg_wm_base", 7, 4, &xdg_wm_base_requests[0], 1, &xdg_wm_base_events[0]}
	xdg_positioner_requests[0] = {"destroy", "", nil}
	xdg_positioner_requests[1] = {"set_size", "ii", &xdg_positioner_requests_types_1[0]}
	xdg_positioner_requests[2] = {"set_anchor_rect", "iiii", &xdg_positioner_requests_types_2[0]}
	xdg_positioner_requests[3] = {"set_anchor", "u", &xdg_positioner_requests_types_3[0]}
	xdg_positioner_requests[4] = {"set_gravity", "u", &xdg_positioner_requests_types_4[0]}
	xdg_positioner_requests[5] = {"set_constraint_adjustment", "u", &xdg_positioner_requests_types_5[0]}
	xdg_positioner_requests[6] = {"set_offset", "ii", &xdg_positioner_requests_types_6[0]}
	xdg_positioner_requests[7] = {"set_reactive", "3", nil}
	xdg_positioner_requests[8] = {"set_parent_size", "3ii", &xdg_positioner_requests_types_8[0]}
	xdg_positioner_requests[9] = {"set_parent_configure", "3u", &xdg_positioner_requests_types_9[0]}
	xdg_positioner_interface = {"xdg_positioner", 7, 10, &xdg_positioner_requests[0], 0, nil}
	xdg_surface_requests[0] = {"destroy", "", nil}
	xdg_surface_requests[1] = {"get_toplevel", "n", &xdg_surface_requests_types_1[0]}
	xdg_surface_requests[2] = {"get_popup", "n?oo", &xdg_surface_requests_types_2[0]}
	xdg_surface_requests[3] = {"set_window_geometry", "iiii", &xdg_surface_requests_types_3[0]}
	xdg_surface_requests[4] = {"ack_configure", "u", &xdg_surface_requests_types_4[0]}
	xdg_surface_events[0] = {"configure", "u", &xdg_surface_events_types_0[0]}
	xdg_surface_interface = {"xdg_surface", 7, 5, &xdg_surface_requests[0], 1, &xdg_surface_events[0]}
	xdg_toplevel_requests[0] = {"destroy", "", nil}
	xdg_toplevel_requests[1] = {"set_parent", "?o", &xdg_toplevel_requests_types_1[0]}
	xdg_toplevel_requests[2] = {"set_title", "s", &xdg_toplevel_requests_types_2[0]}
	xdg_toplevel_requests[3] = {"set_app_id", "s", &xdg_toplevel_requests_types_3[0]}
	xdg_toplevel_requests[4] = {"show_window_menu", "ouii", &xdg_toplevel_requests_types_4[0]}
	xdg_toplevel_requests[5] = {"move", "ou", &xdg_toplevel_requests_types_5[0]}
	xdg_toplevel_requests[6] = {"resize", "ouu", &xdg_toplevel_requests_types_6[0]}
	xdg_toplevel_requests[7] = {"set_max_size", "ii", &xdg_toplevel_requests_types_7[0]}
	xdg_toplevel_requests[8] = {"set_min_size", "ii", &xdg_toplevel_requests_types_8[0]}
	xdg_toplevel_requests[9] = {"set_maximized", "", nil}
	xdg_toplevel_requests[10] = {"unset_maximized", "", nil}
	xdg_toplevel_requests[11] = {"set_fullscreen", "?o", &xdg_toplevel_requests_types_11[0]}
	xdg_toplevel_requests[12] = {"unset_fullscreen", "", nil}
	xdg_toplevel_requests[13] = {"set_minimized", "", nil}
	xdg_toplevel_events[0] = {"configure", "iia", &xdg_toplevel_events_types_0[0]}
	xdg_toplevel_events[1] = {"close", "", nil}
	xdg_toplevel_events[2] = {"configure_bounds", "4ii", &xdg_toplevel_events_types_2[0]}
	xdg_toplevel_events[3] = {"wm_capabilities", "5a", &xdg_toplevel_events_types_3[0]}
	xdg_toplevel_interface = {"xdg_toplevel", 7, 14, &xdg_toplevel_requests[0], 4, &xdg_toplevel_events[0]}
	xdg_popup_requests[0] = {"destroy", "", nil}
	xdg_popup_requests[1] = {"grab", "ou", &xdg_popup_requests_types_1[0]}
	xdg_popup_requests[2] = {"reposition", "3ou", &xdg_popup_requests_types_2[0]}
	xdg_popup_events[0] = {"configure", "iiii", &xdg_popup_events_types_0[0]}
	xdg_popup_events[1] = {"popup_done", "", nil}
	xdg_popup_events[2] = {"repositioned", "3u", &xdg_popup_events_types_2[0]}
	xdg_popup_interface = {"xdg_popup", 7, 3, &xdg_popup_requests[0], 3, &xdg_popup_events[0]}
	zxdg_decoration_manager_v1_requests[0] = {"destroy", "", nil}
	zxdg_decoration_manager_v1_requests[1] = {"get_toplevel_decoration", "no", &zxdg_decoration_manager_v1_requests_types_1[0]}
	zxdg_decoration_manager_v1_interface = {"zxdg_decoration_manager_v1", 2, 2, &zxdg_decoration_manager_v1_requests[0], 0, nil}
	zxdg_toplevel_decoration_v1_requests[0] = {"destroy", "", nil}
	zxdg_toplevel_decoration_v1_requests[1] = {"set_mode", "u", &zxdg_toplevel_decoration_v1_requests_types_1[0]}
	zxdg_toplevel_decoration_v1_requests[2] = {"unset_mode", "", nil}
	zxdg_toplevel_decoration_v1_events[0] = {"configure", "u", &zxdg_toplevel_decoration_v1_events_types_0[0]}
	zxdg_toplevel_decoration_v1_interface = {"zxdg_toplevel_decoration_v1", 2, 3, &zxdg_toplevel_decoration_v1_requests[0], 1, &zxdg_toplevel_decoration_v1_events[0]}
	ext_background_effect_manager_v1_requests[0] = {"destroy", "", nil}
	ext_background_effect_manager_v1_requests[1] = {"get_background_effect", "no", &ext_background_effect_manager_v1_requests_types_1[0]}
	ext_background_effect_manager_v1_events[0] = {"capabilities", "u", &ext_background_effect_manager_v1_events_types_0[0]}
	ext_background_effect_manager_v1_interface = {"ext_background_effect_manager_v1", 1, 2, &ext_background_effect_manager_v1_requests[0], 1, &ext_background_effect_manager_v1_events[0]}
	ext_background_effect_surface_v1_requests[0] = {"destroy", "", nil}
	ext_background_effect_surface_v1_requests[1] = {"set_blur_region", "?o", &ext_background_effect_surface_v1_requests_types_1[0]}
	ext_background_effect_surface_v1_interface = {"ext_background_effect_surface_v1", 1, 2, &ext_background_effect_surface_v1_requests[0], 0, nil}
}

// ---- wl_display ----

wl_display_error_invalid_object :: 0
wl_display_error_invalid_method :: 1
wl_display_error_no_memory :: 2
wl_display_error_implementation :: 3

wl_display_listener :: struct {
	error: proc "c" (data: rawptr, self: ^wl_display, object_id: rawptr, code: u32, message: cstring),
	delete_id: proc "c" (data: rawptr, self: ^wl_display, id: u32),
}

wl_display_add_listener :: proc "contextless" (self: ^wl_display, listener: ^wl_display_listener, data: rawptr) -> c.int {
	return proxy_add_listener(cast(^Proxy)self, cast([^]rawptr)listener, data)
}

wl_display_sync :: proc "contextless" (self: ^wl_display) -> ^wl_callback {
	return cast(^wl_callback)proxy_marshal_flags(cast(^Proxy)self, 0, &wl_callback_interface, proxy_get_version(cast(^Proxy)self), 0, rawptr(nil))
}

wl_display_get_registry :: proc "contextless" (self: ^wl_display) -> ^wl_registry {
	return cast(^wl_registry)proxy_marshal_flags(cast(^Proxy)self, 1, &wl_registry_interface, proxy_get_version(cast(^Proxy)self), 0, rawptr(nil))
}

// ---- wl_registry ----

wl_registry_listener :: struct {
	global: proc "c" (data: rawptr, self: ^wl_registry, name: u32, interface: cstring, version: u32),
	global_remove: proc "c" (data: rawptr, self: ^wl_registry, name: u32),
}

wl_registry_add_listener :: proc "contextless" (self: ^wl_registry, listener: ^wl_registry_listener, data: rawptr) -> c.int {
	return proxy_add_listener(cast(^Proxy)self, cast([^]rawptr)listener, data)
}

wl_registry_bind :: proc "contextless" (self: ^wl_registry, name: u32, interface: ^Interface, version: u32) -> rawptr {
	return rawptr(proxy_marshal_flags(cast(^Proxy)self, 0, interface, version, 0, name, interface.name, version, rawptr(nil)))
}

wl_registry_destroy :: proc "contextless" (self: ^wl_registry) {
	proxy_destroy(cast(^Proxy)self)
}

// ---- wl_callback ----

wl_callback_listener :: struct {
	done: proc "c" (data: rawptr, self: ^wl_callback, callback_data: u32),
}

wl_callback_add_listener :: proc "contextless" (self: ^wl_callback, listener: ^wl_callback_listener, data: rawptr) -> c.int {
	return proxy_add_listener(cast(^Proxy)self, cast([^]rawptr)listener, data)
}

wl_callback_destroy :: proc "contextless" (self: ^wl_callback) {
	proxy_destroy(cast(^Proxy)self)
}

// ---- wl_compositor ----

wl_compositor_create_surface :: proc "contextless" (self: ^wl_compositor) -> ^wl_surface {
	return cast(^wl_surface)proxy_marshal_flags(cast(^Proxy)self, 0, &wl_surface_interface, proxy_get_version(cast(^Proxy)self), 0, rawptr(nil))
}

wl_compositor_create_region :: proc "contextless" (self: ^wl_compositor) -> ^wl_region {
	return cast(^wl_region)proxy_marshal_flags(cast(^Proxy)self, 1, &wl_region_interface, proxy_get_version(cast(^Proxy)self), 0, rawptr(nil))
}

wl_compositor_release :: proc "contextless" (self: ^wl_compositor) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 2, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

// ---- wl_shm_pool ----

wl_shm_pool_error_invalid_format :: 0
wl_shm_pool_error_invalid_stride :: 1

wl_shm_pool_create_buffer :: proc "contextless" (self: ^wl_shm_pool, offset: i32, width: i32, height: i32, stride: i32, format: u32) -> ^wl_buffer {
	return cast(^wl_buffer)proxy_marshal_flags(cast(^Proxy)self, 0, &wl_buffer_interface, proxy_get_version(cast(^Proxy)self), 0, rawptr(nil), offset, width, height, stride, format)
}

wl_shm_pool_destroy :: proc "contextless" (self: ^wl_shm_pool) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 1, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

wl_shm_pool_resize :: proc "contextless" (self: ^wl_shm_pool, size_: i32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 2, nil, proxy_get_version(cast(^Proxy)self), 0, size_)
}

// ---- wl_shm ----

wl_shm_error_invalid_format :: 0
wl_shm_error_invalid_stride :: 1
wl_shm_error_invalid_fd :: 2

wl_shm_format_argb8888 :: 0
wl_shm_format_xrgb8888 :: 1
wl_shm_format_c8 :: 0x20203843
wl_shm_format_rgb332 :: 0x38424752
wl_shm_format_bgr233 :: 0x38524742
wl_shm_format_xrgb4444 :: 0x32315258
wl_shm_format_xbgr4444 :: 0x32314258
wl_shm_format_rgbx4444 :: 0x32315852
wl_shm_format_bgrx4444 :: 0x32315842
wl_shm_format_argb4444 :: 0x32315241
wl_shm_format_abgr4444 :: 0x32314241
wl_shm_format_rgba4444 :: 0x32314152
wl_shm_format_bgra4444 :: 0x32314142
wl_shm_format_xrgb1555 :: 0x35315258
wl_shm_format_xbgr1555 :: 0x35314258
wl_shm_format_rgbx5551 :: 0x35315852
wl_shm_format_bgrx5551 :: 0x35315842
wl_shm_format_argb1555 :: 0x35315241
wl_shm_format_abgr1555 :: 0x35314241
wl_shm_format_rgba5551 :: 0x35314152
wl_shm_format_bgra5551 :: 0x35314142
wl_shm_format_rgb565 :: 0x36314752
wl_shm_format_bgr565 :: 0x36314742
wl_shm_format_rgb888 :: 0x34324752
wl_shm_format_bgr888 :: 0x34324742
wl_shm_format_xbgr8888 :: 0x34324258
wl_shm_format_rgbx8888 :: 0x34325852
wl_shm_format_bgrx8888 :: 0x34325842
wl_shm_format_abgr8888 :: 0x34324241
wl_shm_format_rgba8888 :: 0x34324152
wl_shm_format_bgra8888 :: 0x34324142
wl_shm_format_xrgb2101010 :: 0x30335258
wl_shm_format_xbgr2101010 :: 0x30334258
wl_shm_format_rgbx1010102 :: 0x30335852
wl_shm_format_bgrx1010102 :: 0x30335842
wl_shm_format_argb2101010 :: 0x30335241
wl_shm_format_abgr2101010 :: 0x30334241
wl_shm_format_rgba1010102 :: 0x30334152
wl_shm_format_bgra1010102 :: 0x30334142
wl_shm_format_yuyv :: 0x56595559
wl_shm_format_yvyu :: 0x55595659
wl_shm_format_uyvy :: 0x59565955
wl_shm_format_vyuy :: 0x59555956
wl_shm_format_ayuv :: 0x56555941
wl_shm_format_nv12 :: 0x3231564e
wl_shm_format_nv21 :: 0x3132564e
wl_shm_format_nv16 :: 0x3631564e
wl_shm_format_nv61 :: 0x3136564e
wl_shm_format_yuv410 :: 0x39565559
wl_shm_format_yvu410 :: 0x39555659
wl_shm_format_yuv411 :: 0x31315559
wl_shm_format_yvu411 :: 0x31315659
wl_shm_format_yuv420 :: 0x32315559
wl_shm_format_yvu420 :: 0x32315659
wl_shm_format_yuv422 :: 0x36315559
wl_shm_format_yvu422 :: 0x36315659
wl_shm_format_yuv444 :: 0x34325559
wl_shm_format_yvu444 :: 0x34325659
wl_shm_format_r8 :: 0x20203852
wl_shm_format_r16 :: 0x20363152
wl_shm_format_rg88 :: 0x38384752
wl_shm_format_gr88 :: 0x38385247
wl_shm_format_rg1616 :: 0x32334752
wl_shm_format_gr1616 :: 0x32335247
wl_shm_format_xrgb16161616f :: 0x48345258
wl_shm_format_xbgr16161616f :: 0x48344258
wl_shm_format_argb16161616f :: 0x48345241
wl_shm_format_abgr16161616f :: 0x48344241
wl_shm_format_xyuv8888 :: 0x56555958
wl_shm_format_vuy888 :: 0x34325556
wl_shm_format_vuy101010 :: 0x30335556
wl_shm_format_y210 :: 0x30313259
wl_shm_format_y212 :: 0x32313259
wl_shm_format_y216 :: 0x36313259
wl_shm_format_y410 :: 0x30313459
wl_shm_format_y412 :: 0x32313459
wl_shm_format_y416 :: 0x36313459
wl_shm_format_xvyu2101010 :: 0x30335658
wl_shm_format_xvyu12_16161616 :: 0x36335658
wl_shm_format_xvyu16161616 :: 0x38345658
wl_shm_format_y0l0 :: 0x304c3059
wl_shm_format_x0l0 :: 0x304c3058
wl_shm_format_y0l2 :: 0x324c3059
wl_shm_format_x0l2 :: 0x324c3058
wl_shm_format_yuv420_8bit :: 0x38305559
wl_shm_format_yuv420_10bit :: 0x30315559
wl_shm_format_xrgb8888_a8 :: 0x38415258
wl_shm_format_xbgr8888_a8 :: 0x38414258
wl_shm_format_rgbx8888_a8 :: 0x38415852
wl_shm_format_bgrx8888_a8 :: 0x38415842
wl_shm_format_rgb888_a8 :: 0x38413852
wl_shm_format_bgr888_a8 :: 0x38413842
wl_shm_format_rgb565_a8 :: 0x38413552
wl_shm_format_bgr565_a8 :: 0x38413542
wl_shm_format_nv24 :: 0x3432564e
wl_shm_format_nv42 :: 0x3234564e
wl_shm_format_p210 :: 0x30313250
wl_shm_format_p010 :: 0x30313050
wl_shm_format_p012 :: 0x32313050
wl_shm_format_p016 :: 0x36313050
wl_shm_format_axbxgxrx106106106106 :: 0x30314241
wl_shm_format_nv15 :: 0x3531564e
wl_shm_format_q410 :: 0x30313451
wl_shm_format_q401 :: 0x31303451
wl_shm_format_xrgb16161616 :: 0x38345258
wl_shm_format_xbgr16161616 :: 0x38344258
wl_shm_format_argb16161616 :: 0x38345241
wl_shm_format_abgr16161616 :: 0x38344241
wl_shm_format_c1 :: 0x20203143
wl_shm_format_c2 :: 0x20203243
wl_shm_format_c4 :: 0x20203443
wl_shm_format_d1 :: 0x20203144
wl_shm_format_d2 :: 0x20203244
wl_shm_format_d4 :: 0x20203444
wl_shm_format_d8 :: 0x20203844
wl_shm_format_r1 :: 0x20203152
wl_shm_format_r2 :: 0x20203252
wl_shm_format_r4 :: 0x20203452
wl_shm_format_r10 :: 0x20303152
wl_shm_format_r12 :: 0x20323152
wl_shm_format_avuy8888 :: 0x59555641
wl_shm_format_xvuy8888 :: 0x59555658
wl_shm_format_p030 :: 0x30333050
wl_shm_format_rgb161616 :: 0x38344752
wl_shm_format_bgr161616 :: 0x38344742
wl_shm_format_r16f :: 0x48202052
wl_shm_format_gr1616f :: 0x48205247
wl_shm_format_bgr161616f :: 0x48524742
wl_shm_format_r32f :: 0x46202052
wl_shm_format_gr3232f :: 0x46205247
wl_shm_format_bgr323232f :: 0x46524742
wl_shm_format_abgr32323232f :: 0x46384241
wl_shm_format_nv20 :: 0x3032564e
wl_shm_format_nv30 :: 0x3033564e
wl_shm_format_s010 :: 0x30313053
wl_shm_format_s210 :: 0x30313253
wl_shm_format_s410 :: 0x30313453
wl_shm_format_s012 :: 0x32313053
wl_shm_format_s212 :: 0x32313253
wl_shm_format_s412 :: 0x32313453
wl_shm_format_s016 :: 0x36313053
wl_shm_format_s216 :: 0x36313253
wl_shm_format_s416 :: 0x36313453
wl_shm_format_xvuy2101010 :: 0x30335958
wl_shm_format_p230 :: 0x30333250
wl_shm_format_t430 :: 0x30333454
wl_shm_format_y8 :: 0x59455247
wl_shm_format_xyyy2101010 :: 0x34415059

wl_shm_listener :: struct {
	format: proc "c" (data: rawptr, self: ^wl_shm, format: u32),
}

wl_shm_add_listener :: proc "contextless" (self: ^wl_shm, listener: ^wl_shm_listener, data: rawptr) -> c.int {
	return proxy_add_listener(cast(^Proxy)self, cast([^]rawptr)listener, data)
}

wl_shm_create_pool :: proc "contextless" (self: ^wl_shm, fd: i32, size_: i32) -> ^wl_shm_pool {
	return cast(^wl_shm_pool)proxy_marshal_flags(cast(^Proxy)self, 0, &wl_shm_pool_interface, proxy_get_version(cast(^Proxy)self), 0, rawptr(nil), fd, size_)
}

wl_shm_release :: proc "contextless" (self: ^wl_shm) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 1, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

// ---- wl_buffer ----

wl_buffer_listener :: struct {
	release: proc "c" (data: rawptr, self: ^wl_buffer),
}

wl_buffer_add_listener :: proc "contextless" (self: ^wl_buffer, listener: ^wl_buffer_listener, data: rawptr) -> c.int {
	return proxy_add_listener(cast(^Proxy)self, cast([^]rawptr)listener, data)
}

wl_buffer_destroy :: proc "contextless" (self: ^wl_buffer) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

// ---- wl_data_offer ----

wl_data_offer_error_invalid_finish :: 0
wl_data_offer_error_invalid_action_mask :: 1
wl_data_offer_error_invalid_action :: 2
wl_data_offer_error_invalid_offer :: 3

wl_data_offer_listener :: struct {
	offer: proc "c" (data: rawptr, self: ^wl_data_offer, mime_type: cstring),
	source_actions: proc "c" (data: rawptr, self: ^wl_data_offer, source_actions: u32),
	action: proc "c" (data: rawptr, self: ^wl_data_offer, dnd_action: u32),
}

wl_data_offer_add_listener :: proc "contextless" (self: ^wl_data_offer, listener: ^wl_data_offer_listener, data: rawptr) -> c.int {
	return proxy_add_listener(cast(^Proxy)self, cast([^]rawptr)listener, data)
}

wl_data_offer_accept :: proc "contextless" (self: ^wl_data_offer, serial: u32, mime_type: cstring) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), 0, serial, mime_type)
}

wl_data_offer_receive :: proc "contextless" (self: ^wl_data_offer, mime_type: cstring, fd: i32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 1, nil, proxy_get_version(cast(^Proxy)self), 0, mime_type, fd)
}

wl_data_offer_destroy :: proc "contextless" (self: ^wl_data_offer) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 2, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

wl_data_offer_finish :: proc "contextless" (self: ^wl_data_offer) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 3, nil, proxy_get_version(cast(^Proxy)self), 0)
}

wl_data_offer_set_actions :: proc "contextless" (self: ^wl_data_offer, dnd_actions: u32, preferred_action: u32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 4, nil, proxy_get_version(cast(^Proxy)self), 0, dnd_actions, preferred_action)
}

// ---- wl_data_source ----

wl_data_source_error_invalid_action_mask :: 0
wl_data_source_error_invalid_source :: 1

wl_data_source_listener :: struct {
	target: proc "c" (data: rawptr, self: ^wl_data_source, mime_type: cstring),
	send: proc "c" (data: rawptr, self: ^wl_data_source, mime_type: cstring, fd: i32),
	cancelled: proc "c" (data: rawptr, self: ^wl_data_source),
	dnd_drop_performed: proc "c" (data: rawptr, self: ^wl_data_source),
	dnd_finished: proc "c" (data: rawptr, self: ^wl_data_source),
	action: proc "c" (data: rawptr, self: ^wl_data_source, dnd_action: u32),
}

wl_data_source_add_listener :: proc "contextless" (self: ^wl_data_source, listener: ^wl_data_source_listener, data: rawptr) -> c.int {
	return proxy_add_listener(cast(^Proxy)self, cast([^]rawptr)listener, data)
}

wl_data_source_offer :: proc "contextless" (self: ^wl_data_source, mime_type: cstring) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), 0, mime_type)
}

wl_data_source_destroy :: proc "contextless" (self: ^wl_data_source) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 1, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

wl_data_source_set_actions :: proc "contextless" (self: ^wl_data_source, dnd_actions: u32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 2, nil, proxy_get_version(cast(^Proxy)self), 0, dnd_actions)
}

// ---- wl_data_device ----

wl_data_device_error_role :: 0
wl_data_device_error_used_source :: 1

wl_data_device_listener :: struct {
	data_offer: proc "c" (data: rawptr, self: ^wl_data_device, id: ^wl_data_offer),
	enter: proc "c" (data: rawptr, self: ^wl_data_device, serial: u32, surface: ^wl_surface, x: Fixed, y: Fixed, id: ^wl_data_offer),
	leave: proc "c" (data: rawptr, self: ^wl_data_device),
	motion: proc "c" (data: rawptr, self: ^wl_data_device, time: u32, x: Fixed, y: Fixed),
	drop: proc "c" (data: rawptr, self: ^wl_data_device),
	selection: proc "c" (data: rawptr, self: ^wl_data_device, id: ^wl_data_offer),
}

wl_data_device_add_listener :: proc "contextless" (self: ^wl_data_device, listener: ^wl_data_device_listener, data: rawptr) -> c.int {
	return proxy_add_listener(cast(^Proxy)self, cast([^]rawptr)listener, data)
}

wl_data_device_start_drag :: proc "contextless" (self: ^wl_data_device, source: ^wl_data_source, origin: ^wl_surface, icon: ^wl_surface, serial: u32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), 0, rawptr(source), rawptr(origin), rawptr(icon), serial)
}

wl_data_device_set_selection :: proc "contextless" (self: ^wl_data_device, source: ^wl_data_source, serial: u32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 1, nil, proxy_get_version(cast(^Proxy)self), 0, rawptr(source), serial)
}

wl_data_device_release :: proc "contextless" (self: ^wl_data_device) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 2, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

// ---- wl_data_device_manager ----

wl_data_device_manager_dnd_action_none :: 0
wl_data_device_manager_dnd_action_copy :: 1
wl_data_device_manager_dnd_action_move :: 2
wl_data_device_manager_dnd_action_ask :: 4

wl_data_device_manager_create_data_source :: proc "contextless" (self: ^wl_data_device_manager) -> ^wl_data_source {
	return cast(^wl_data_source)proxy_marshal_flags(cast(^Proxy)self, 0, &wl_data_source_interface, proxy_get_version(cast(^Proxy)self), 0, rawptr(nil))
}

wl_data_device_manager_get_data_device :: proc "contextless" (self: ^wl_data_device_manager, seat: ^wl_seat) -> ^wl_data_device {
	return cast(^wl_data_device)proxy_marshal_flags(cast(^Proxy)self, 1, &wl_data_device_interface, proxy_get_version(cast(^Proxy)self), 0, rawptr(nil), rawptr(seat))
}

wl_data_device_manager_release :: proc "contextless" (self: ^wl_data_device_manager) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 2, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

// ---- wl_shell ----

wl_shell_error_role :: 0

wl_shell_get_shell_surface :: proc "contextless" (self: ^wl_shell, surface: ^wl_surface) -> ^wl_shell_surface {
	return cast(^wl_shell_surface)proxy_marshal_flags(cast(^Proxy)self, 0, &wl_shell_surface_interface, proxy_get_version(cast(^Proxy)self), 0, rawptr(nil), rawptr(surface))
}

wl_shell_destroy :: proc "contextless" (self: ^wl_shell) {
	proxy_destroy(cast(^Proxy)self)
}

// ---- wl_shell_surface ----

wl_shell_surface_resize_none :: 0
wl_shell_surface_resize_top :: 1
wl_shell_surface_resize_bottom :: 2
wl_shell_surface_resize_left :: 4
wl_shell_surface_resize_top_left :: 5
wl_shell_surface_resize_bottom_left :: 6
wl_shell_surface_resize_right :: 8
wl_shell_surface_resize_top_right :: 9
wl_shell_surface_resize_bottom_right :: 10

wl_shell_surface_transient_inactive :: 0x1

wl_shell_surface_fullscreen_method_default :: 0
wl_shell_surface_fullscreen_method_scale :: 1
wl_shell_surface_fullscreen_method_driver :: 2
wl_shell_surface_fullscreen_method_fill :: 3

wl_shell_surface_listener :: struct {
	ping: proc "c" (data: rawptr, self: ^wl_shell_surface, serial: u32),
	configure: proc "c" (data: rawptr, self: ^wl_shell_surface, edges: u32, width: i32, height: i32),
	popup_done: proc "c" (data: rawptr, self: ^wl_shell_surface),
}

wl_shell_surface_add_listener :: proc "contextless" (self: ^wl_shell_surface, listener: ^wl_shell_surface_listener, data: rawptr) -> c.int {
	return proxy_add_listener(cast(^Proxy)self, cast([^]rawptr)listener, data)
}

wl_shell_surface_pong :: proc "contextless" (self: ^wl_shell_surface, serial: u32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), 0, serial)
}

wl_shell_surface_move :: proc "contextless" (self: ^wl_shell_surface, seat: ^wl_seat, serial: u32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 1, nil, proxy_get_version(cast(^Proxy)self), 0, rawptr(seat), serial)
}

wl_shell_surface_resize :: proc "contextless" (self: ^wl_shell_surface, seat: ^wl_seat, serial: u32, edges: u32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 2, nil, proxy_get_version(cast(^Proxy)self), 0, rawptr(seat), serial, edges)
}

wl_shell_surface_set_toplevel :: proc "contextless" (self: ^wl_shell_surface) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 3, nil, proxy_get_version(cast(^Proxy)self), 0)
}

wl_shell_surface_set_transient :: proc "contextless" (self: ^wl_shell_surface, parent: ^wl_surface, x: i32, y: i32, flags: u32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 4, nil, proxy_get_version(cast(^Proxy)self), 0, rawptr(parent), x, y, flags)
}

wl_shell_surface_set_fullscreen :: proc "contextless" (self: ^wl_shell_surface, method: u32, framerate: u32, output: ^wl_output) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 5, nil, proxy_get_version(cast(^Proxy)self), 0, method, framerate, rawptr(output))
}

wl_shell_surface_set_popup :: proc "contextless" (self: ^wl_shell_surface, seat: ^wl_seat, serial: u32, parent: ^wl_surface, x: i32, y: i32, flags: u32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 6, nil, proxy_get_version(cast(^Proxy)self), 0, rawptr(seat), serial, rawptr(parent), x, y, flags)
}

wl_shell_surface_set_maximized :: proc "contextless" (self: ^wl_shell_surface, output: ^wl_output) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 7, nil, proxy_get_version(cast(^Proxy)self), 0, rawptr(output))
}

wl_shell_surface_set_title :: proc "contextless" (self: ^wl_shell_surface, title: cstring) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 8, nil, proxy_get_version(cast(^Proxy)self), 0, title)
}

wl_shell_surface_set_class :: proc "contextless" (self: ^wl_shell_surface, class_: cstring) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 9, nil, proxy_get_version(cast(^Proxy)self), 0, class_)
}

wl_shell_surface_destroy :: proc "contextless" (self: ^wl_shell_surface) {
	proxy_destroy(cast(^Proxy)self)
}

// ---- wl_surface ----

wl_surface_error_invalid_scale :: 0
wl_surface_error_invalid_transform :: 1
wl_surface_error_invalid_size :: 2
wl_surface_error_invalid_offset :: 3
wl_surface_error_defunct_role_object :: 4
wl_surface_error_no_buffer :: 5

wl_surface_listener :: struct {
	enter: proc "c" (data: rawptr, self: ^wl_surface, output: ^wl_output),
	leave: proc "c" (data: rawptr, self: ^wl_surface, output: ^wl_output),
	preferred_buffer_scale: proc "c" (data: rawptr, self: ^wl_surface, factor: i32),
	preferred_buffer_transform: proc "c" (data: rawptr, self: ^wl_surface, transform: u32),
}

wl_surface_add_listener :: proc "contextless" (self: ^wl_surface, listener: ^wl_surface_listener, data: rawptr) -> c.int {
	return proxy_add_listener(cast(^Proxy)self, cast([^]rawptr)listener, data)
}

wl_surface_destroy :: proc "contextless" (self: ^wl_surface) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

wl_surface_attach :: proc "contextless" (self: ^wl_surface, buffer: ^wl_buffer, x: i32, y: i32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 1, nil, proxy_get_version(cast(^Proxy)self), 0, rawptr(buffer), x, y)
}

wl_surface_damage :: proc "contextless" (self: ^wl_surface, x: i32, y: i32, width: i32, height: i32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 2, nil, proxy_get_version(cast(^Proxy)self), 0, x, y, width, height)
}

wl_surface_frame :: proc "contextless" (self: ^wl_surface) -> ^wl_callback {
	return cast(^wl_callback)proxy_marshal_flags(cast(^Proxy)self, 3, &wl_callback_interface, proxy_get_version(cast(^Proxy)self), 0, rawptr(nil))
}

wl_surface_set_opaque_region :: proc "contextless" (self: ^wl_surface, region: ^wl_region) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 4, nil, proxy_get_version(cast(^Proxy)self), 0, rawptr(region))
}

wl_surface_set_input_region :: proc "contextless" (self: ^wl_surface, region: ^wl_region) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 5, nil, proxy_get_version(cast(^Proxy)self), 0, rawptr(region))
}

wl_surface_commit :: proc "contextless" (self: ^wl_surface) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 6, nil, proxy_get_version(cast(^Proxy)self), 0)
}

wl_surface_set_buffer_transform :: proc "contextless" (self: ^wl_surface, transform: i32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 7, nil, proxy_get_version(cast(^Proxy)self), 0, transform)
}

wl_surface_set_buffer_scale :: proc "contextless" (self: ^wl_surface, scale: i32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 8, nil, proxy_get_version(cast(^Proxy)self), 0, scale)
}

wl_surface_damage_buffer :: proc "contextless" (self: ^wl_surface, x: i32, y: i32, width: i32, height: i32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 9, nil, proxy_get_version(cast(^Proxy)self), 0, x, y, width, height)
}

wl_surface_offset :: proc "contextless" (self: ^wl_surface, x: i32, y: i32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 10, nil, proxy_get_version(cast(^Proxy)self), 0, x, y)
}

wl_surface_get_release :: proc "contextless" (self: ^wl_surface) -> ^wl_callback {
	return cast(^wl_callback)proxy_marshal_flags(cast(^Proxy)self, 11, &wl_callback_interface, proxy_get_version(cast(^Proxy)self), 0, rawptr(nil))
}

// ---- wl_seat ----

wl_seat_capability_pointer :: 1
wl_seat_capability_keyboard :: 2
wl_seat_capability_touch :: 4

wl_seat_error_missing_capability :: 0

wl_seat_listener :: struct {
	capabilities: proc "c" (data: rawptr, self: ^wl_seat, capabilities: u32),
	name: proc "c" (data: rawptr, self: ^wl_seat, name: cstring),
}

wl_seat_add_listener :: proc "contextless" (self: ^wl_seat, listener: ^wl_seat_listener, data: rawptr) -> c.int {
	return proxy_add_listener(cast(^Proxy)self, cast([^]rawptr)listener, data)
}

wl_seat_get_pointer :: proc "contextless" (self: ^wl_seat) -> ^wl_pointer {
	return cast(^wl_pointer)proxy_marshal_flags(cast(^Proxy)self, 0, &wl_pointer_interface, proxy_get_version(cast(^Proxy)self), 0, rawptr(nil))
}

wl_seat_get_keyboard :: proc "contextless" (self: ^wl_seat) -> ^wl_keyboard {
	return cast(^wl_keyboard)proxy_marshal_flags(cast(^Proxy)self, 1, &wl_keyboard_interface, proxy_get_version(cast(^Proxy)self), 0, rawptr(nil))
}

wl_seat_get_touch :: proc "contextless" (self: ^wl_seat) -> ^wl_touch {
	return cast(^wl_touch)proxy_marshal_flags(cast(^Proxy)self, 2, &wl_touch_interface, proxy_get_version(cast(^Proxy)self), 0, rawptr(nil))
}

wl_seat_release :: proc "contextless" (self: ^wl_seat) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 3, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

// ---- wl_pointer ----

wl_pointer_error_role :: 0

wl_pointer_button_state_released :: 0
wl_pointer_button_state_pressed :: 1

wl_pointer_axis_vertical_scroll :: 0
wl_pointer_axis_horizontal_scroll :: 1

wl_pointer_axis_source_wheel :: 0
wl_pointer_axis_source_finger :: 1
wl_pointer_axis_source_continuous :: 2
wl_pointer_axis_source_wheel_tilt :: 3

wl_pointer_axis_relative_direction_identical :: 0
wl_pointer_axis_relative_direction_inverted :: 1

wl_pointer_listener :: struct {
	enter: proc "c" (data: rawptr, self: ^wl_pointer, serial: u32, surface: ^wl_surface, surface_x: Fixed, surface_y: Fixed),
	leave: proc "c" (data: rawptr, self: ^wl_pointer, serial: u32, surface: ^wl_surface),
	motion: proc "c" (data: rawptr, self: ^wl_pointer, time: u32, surface_x: Fixed, surface_y: Fixed),
	button: proc "c" (data: rawptr, self: ^wl_pointer, serial: u32, time: u32, button: u32, state: u32),
	axis: proc "c" (data: rawptr, self: ^wl_pointer, time: u32, axis: u32, value: Fixed),
	frame: proc "c" (data: rawptr, self: ^wl_pointer),
	axis_source: proc "c" (data: rawptr, self: ^wl_pointer, axis_source: u32),
	axis_stop: proc "c" (data: rawptr, self: ^wl_pointer, time: u32, axis: u32),
	axis_discrete: proc "c" (data: rawptr, self: ^wl_pointer, axis: u32, discrete: i32),
	axis_value120: proc "c" (data: rawptr, self: ^wl_pointer, axis: u32, value120: i32),
	axis_relative_direction: proc "c" (data: rawptr, self: ^wl_pointer, axis: u32, direction: u32),
	warp: proc "c" (data: rawptr, self: ^wl_pointer, surface_x: Fixed, surface_y: Fixed),
}

wl_pointer_add_listener :: proc "contextless" (self: ^wl_pointer, listener: ^wl_pointer_listener, data: rawptr) -> c.int {
	return proxy_add_listener(cast(^Proxy)self, cast([^]rawptr)listener, data)
}

wl_pointer_set_cursor :: proc "contextless" (self: ^wl_pointer, serial: u32, surface: ^wl_surface, hotspot_x: i32, hotspot_y: i32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), 0, serial, rawptr(surface), hotspot_x, hotspot_y)
}

wl_pointer_release :: proc "contextless" (self: ^wl_pointer) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 1, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

// ---- wl_keyboard ----

wl_keyboard_keymap_format_no_keymap :: 0
wl_keyboard_keymap_format_xkb_v1 :: 1

wl_keyboard_key_state_released :: 0
wl_keyboard_key_state_pressed :: 1
wl_keyboard_key_state_repeated :: 2

wl_keyboard_listener :: struct {
	keymap: proc "c" (data: rawptr, self: ^wl_keyboard, format: u32, fd: i32, size_: u32),
	enter: proc "c" (data: rawptr, self: ^wl_keyboard, serial: u32, surface: ^wl_surface, keys: ^Array),
	leave: proc "c" (data: rawptr, self: ^wl_keyboard, serial: u32, surface: ^wl_surface),
	key: proc "c" (data: rawptr, self: ^wl_keyboard, serial: u32, time: u32, key: u32, state: u32),
	modifiers: proc "c" (data: rawptr, self: ^wl_keyboard, serial: u32, mods_depressed: u32, mods_latched: u32, mods_locked: u32, group: u32),
	repeat_info: proc "c" (data: rawptr, self: ^wl_keyboard, rate: i32, delay: i32),
}

wl_keyboard_add_listener :: proc "contextless" (self: ^wl_keyboard, listener: ^wl_keyboard_listener, data: rawptr) -> c.int {
	return proxy_add_listener(cast(^Proxy)self, cast([^]rawptr)listener, data)
}

wl_keyboard_release :: proc "contextless" (self: ^wl_keyboard) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

// ---- wl_touch ----

wl_touch_listener :: struct {
	down: proc "c" (data: rawptr, self: ^wl_touch, serial: u32, time: u32, surface: ^wl_surface, id: i32, x: Fixed, y: Fixed),
	up: proc "c" (data: rawptr, self: ^wl_touch, serial: u32, time: u32, id: i32),
	motion: proc "c" (data: rawptr, self: ^wl_touch, time: u32, id: i32, x: Fixed, y: Fixed),
	frame: proc "c" (data: rawptr, self: ^wl_touch),
	cancel: proc "c" (data: rawptr, self: ^wl_touch),
	shape: proc "c" (data: rawptr, self: ^wl_touch, id: i32, major: Fixed, minor: Fixed),
	orientation: proc "c" (data: rawptr, self: ^wl_touch, id: i32, orientation: Fixed),
}

wl_touch_add_listener :: proc "contextless" (self: ^wl_touch, listener: ^wl_touch_listener, data: rawptr) -> c.int {
	return proxy_add_listener(cast(^Proxy)self, cast([^]rawptr)listener, data)
}

wl_touch_release :: proc "contextless" (self: ^wl_touch) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

// ---- wl_output ----

wl_output_subpixel_unknown :: 0
wl_output_subpixel_none :: 1
wl_output_subpixel_horizontal_rgb :: 2
wl_output_subpixel_horizontal_bgr :: 3
wl_output_subpixel_vertical_rgb :: 4
wl_output_subpixel_vertical_bgr :: 5

wl_output_transform_normal :: 0
wl_output_transform_90 :: 1
wl_output_transform_180 :: 2
wl_output_transform_270 :: 3
wl_output_transform_flipped :: 4
wl_output_transform_flipped_90 :: 5
wl_output_transform_flipped_180 :: 6
wl_output_transform_flipped_270 :: 7

wl_output_mode_current :: 0x1
wl_output_mode_preferred :: 0x2

wl_output_listener :: struct {
	geometry: proc "c" (data: rawptr, self: ^wl_output, x: i32, y: i32, physical_width: i32, physical_height: i32, subpixel: i32, make: cstring, model: cstring, transform: i32),
	mode: proc "c" (data: rawptr, self: ^wl_output, flags: u32, width: i32, height: i32, refresh: i32),
	done: proc "c" (data: rawptr, self: ^wl_output),
	scale: proc "c" (data: rawptr, self: ^wl_output, factor: i32),
	name: proc "c" (data: rawptr, self: ^wl_output, name: cstring),
	description: proc "c" (data: rawptr, self: ^wl_output, description: cstring),
}

wl_output_add_listener :: proc "contextless" (self: ^wl_output, listener: ^wl_output_listener, data: rawptr) -> c.int {
	return proxy_add_listener(cast(^Proxy)self, cast([^]rawptr)listener, data)
}

wl_output_release :: proc "contextless" (self: ^wl_output) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

// ---- wl_region ----

wl_region_destroy :: proc "contextless" (self: ^wl_region) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

wl_region_add :: proc "contextless" (self: ^wl_region, x: i32, y: i32, width: i32, height: i32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 1, nil, proxy_get_version(cast(^Proxy)self), 0, x, y, width, height)
}

wl_region_subtract :: proc "contextless" (self: ^wl_region, x: i32, y: i32, width: i32, height: i32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 2, nil, proxy_get_version(cast(^Proxy)self), 0, x, y, width, height)
}

// ---- wl_subcompositor ----

wl_subcompositor_error_bad_surface :: 0
wl_subcompositor_error_bad_parent :: 1

wl_subcompositor_destroy :: proc "contextless" (self: ^wl_subcompositor) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

wl_subcompositor_get_subsurface :: proc "contextless" (self: ^wl_subcompositor, surface: ^wl_surface, parent: ^wl_surface) -> ^wl_subsurface {
	return cast(^wl_subsurface)proxy_marshal_flags(cast(^Proxy)self, 1, &wl_subsurface_interface, proxy_get_version(cast(^Proxy)self), 0, rawptr(nil), rawptr(surface), rawptr(parent))
}

// ---- wl_subsurface ----

wl_subsurface_error_bad_surface :: 0

wl_subsurface_destroy :: proc "contextless" (self: ^wl_subsurface) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

wl_subsurface_set_position :: proc "contextless" (self: ^wl_subsurface, x: i32, y: i32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 1, nil, proxy_get_version(cast(^Proxy)self), 0, x, y)
}

wl_subsurface_place_above :: proc "contextless" (self: ^wl_subsurface, sibling: ^wl_surface) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 2, nil, proxy_get_version(cast(^Proxy)self), 0, rawptr(sibling))
}

wl_subsurface_place_below :: proc "contextless" (self: ^wl_subsurface, sibling: ^wl_surface) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 3, nil, proxy_get_version(cast(^Proxy)self), 0, rawptr(sibling))
}

wl_subsurface_set_sync :: proc "contextless" (self: ^wl_subsurface) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 4, nil, proxy_get_version(cast(^Proxy)self), 0)
}

wl_subsurface_set_desync :: proc "contextless" (self: ^wl_subsurface) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 5, nil, proxy_get_version(cast(^Proxy)self), 0)
}

// ---- wl_fixes ----

wl_fixes_error_invalid_ack_remove :: 0

wl_fixes_destroy :: proc "contextless" (self: ^wl_fixes) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

wl_fixes_destroy_registry :: proc "contextless" (self: ^wl_fixes, registry: ^wl_registry) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 1, nil, proxy_get_version(cast(^Proxy)self), 0, rawptr(registry))
}

wl_fixes_ack_global_remove :: proc "contextless" (self: ^wl_fixes, registry: ^wl_registry, name: u32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 2, nil, proxy_get_version(cast(^Proxy)self), 0, rawptr(registry), name)
}

// ---- xdg_wm_base ----

xdg_wm_base_error_role :: 0
xdg_wm_base_error_defunct_surfaces :: 1
xdg_wm_base_error_not_the_topmost_popup :: 2
xdg_wm_base_error_invalid_popup_parent :: 3
xdg_wm_base_error_invalid_surface_state :: 4
xdg_wm_base_error_invalid_positioner :: 5
xdg_wm_base_error_unresponsive :: 6

xdg_wm_base_listener :: struct {
	ping: proc "c" (data: rawptr, self: ^xdg_wm_base, serial: u32),
}

xdg_wm_base_add_listener :: proc "contextless" (self: ^xdg_wm_base, listener: ^xdg_wm_base_listener, data: rawptr) -> c.int {
	return proxy_add_listener(cast(^Proxy)self, cast([^]rawptr)listener, data)
}

xdg_wm_base_destroy :: proc "contextless" (self: ^xdg_wm_base) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

xdg_wm_base_create_positioner :: proc "contextless" (self: ^xdg_wm_base) -> ^xdg_positioner {
	return cast(^xdg_positioner)proxy_marshal_flags(cast(^Proxy)self, 1, &xdg_positioner_interface, proxy_get_version(cast(^Proxy)self), 0, rawptr(nil))
}

xdg_wm_base_get_xdg_surface :: proc "contextless" (self: ^xdg_wm_base, surface: ^wl_surface) -> ^xdg_surface {
	return cast(^xdg_surface)proxy_marshal_flags(cast(^Proxy)self, 2, &xdg_surface_interface, proxy_get_version(cast(^Proxy)self), 0, rawptr(nil), rawptr(surface))
}

xdg_wm_base_pong :: proc "contextless" (self: ^xdg_wm_base, serial: u32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 3, nil, proxy_get_version(cast(^Proxy)self), 0, serial)
}

// ---- xdg_positioner ----

xdg_positioner_error_invalid_input :: 0

xdg_positioner_anchor_none :: 0
xdg_positioner_anchor_top :: 1
xdg_positioner_anchor_bottom :: 2
xdg_positioner_anchor_left :: 3
xdg_positioner_anchor_right :: 4
xdg_positioner_anchor_top_left :: 5
xdg_positioner_anchor_bottom_left :: 6
xdg_positioner_anchor_top_right :: 7
xdg_positioner_anchor_bottom_right :: 8

xdg_positioner_gravity_none :: 0
xdg_positioner_gravity_top :: 1
xdg_positioner_gravity_bottom :: 2
xdg_positioner_gravity_left :: 3
xdg_positioner_gravity_right :: 4
xdg_positioner_gravity_top_left :: 5
xdg_positioner_gravity_bottom_left :: 6
xdg_positioner_gravity_top_right :: 7
xdg_positioner_gravity_bottom_right :: 8

xdg_positioner_constraint_adjustment_none :: 0
xdg_positioner_constraint_adjustment_slide_x :: 1
xdg_positioner_constraint_adjustment_slide_y :: 2
xdg_positioner_constraint_adjustment_flip_x :: 4
xdg_positioner_constraint_adjustment_flip_y :: 8
xdg_positioner_constraint_adjustment_resize_x :: 16
xdg_positioner_constraint_adjustment_resize_y :: 32

xdg_positioner_destroy :: proc "contextless" (self: ^xdg_positioner) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

xdg_positioner_set_size :: proc "contextless" (self: ^xdg_positioner, width: i32, height: i32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 1, nil, proxy_get_version(cast(^Proxy)self), 0, width, height)
}

xdg_positioner_set_anchor_rect :: proc "contextless" (self: ^xdg_positioner, x: i32, y: i32, width: i32, height: i32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 2, nil, proxy_get_version(cast(^Proxy)self), 0, x, y, width, height)
}

xdg_positioner_set_anchor :: proc "contextless" (self: ^xdg_positioner, anchor: u32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 3, nil, proxy_get_version(cast(^Proxy)self), 0, anchor)
}

xdg_positioner_set_gravity :: proc "contextless" (self: ^xdg_positioner, gravity: u32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 4, nil, proxy_get_version(cast(^Proxy)self), 0, gravity)
}

xdg_positioner_set_constraint_adjustment :: proc "contextless" (self: ^xdg_positioner, constraint_adjustment: u32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 5, nil, proxy_get_version(cast(^Proxy)self), 0, constraint_adjustment)
}

xdg_positioner_set_offset :: proc "contextless" (self: ^xdg_positioner, x: i32, y: i32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 6, nil, proxy_get_version(cast(^Proxy)self), 0, x, y)
}

xdg_positioner_set_reactive :: proc "contextless" (self: ^xdg_positioner) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 7, nil, proxy_get_version(cast(^Proxy)self), 0)
}

xdg_positioner_set_parent_size :: proc "contextless" (self: ^xdg_positioner, parent_width: i32, parent_height: i32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 8, nil, proxy_get_version(cast(^Proxy)self), 0, parent_width, parent_height)
}

xdg_positioner_set_parent_configure :: proc "contextless" (self: ^xdg_positioner, serial: u32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 9, nil, proxy_get_version(cast(^Proxy)self), 0, serial)
}

// ---- xdg_surface ----

xdg_surface_error_not_constructed :: 1
xdg_surface_error_already_constructed :: 2
xdg_surface_error_unconfigured_buffer :: 3
xdg_surface_error_invalid_serial :: 4
xdg_surface_error_invalid_size :: 5
xdg_surface_error_defunct_role_object :: 6

xdg_surface_listener :: struct {
	configure: proc "c" (data: rawptr, self: ^xdg_surface, serial: u32),
}

xdg_surface_add_listener :: proc "contextless" (self: ^xdg_surface, listener: ^xdg_surface_listener, data: rawptr) -> c.int {
	return proxy_add_listener(cast(^Proxy)self, cast([^]rawptr)listener, data)
}

xdg_surface_destroy :: proc "contextless" (self: ^xdg_surface) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

xdg_surface_get_toplevel :: proc "contextless" (self: ^xdg_surface) -> ^xdg_toplevel {
	return cast(^xdg_toplevel)proxy_marshal_flags(cast(^Proxy)self, 1, &xdg_toplevel_interface, proxy_get_version(cast(^Proxy)self), 0, rawptr(nil))
}

xdg_surface_get_popup :: proc "contextless" (self: ^xdg_surface, parent: ^xdg_surface, positioner: ^xdg_positioner) -> ^xdg_popup {
	return cast(^xdg_popup)proxy_marshal_flags(cast(^Proxy)self, 2, &xdg_popup_interface, proxy_get_version(cast(^Proxy)self), 0, rawptr(nil), rawptr(parent), rawptr(positioner))
}

xdg_surface_set_window_geometry :: proc "contextless" (self: ^xdg_surface, x: i32, y: i32, width: i32, height: i32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 3, nil, proxy_get_version(cast(^Proxy)self), 0, x, y, width, height)
}

xdg_surface_ack_configure :: proc "contextless" (self: ^xdg_surface, serial: u32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 4, nil, proxy_get_version(cast(^Proxy)self), 0, serial)
}

// ---- xdg_toplevel ----

xdg_toplevel_error_invalid_resize_edge :: 0
xdg_toplevel_error_invalid_parent :: 1
xdg_toplevel_error_invalid_size :: 2

xdg_toplevel_resize_edge_none :: 0
xdg_toplevel_resize_edge_top :: 1
xdg_toplevel_resize_edge_bottom :: 2
xdg_toplevel_resize_edge_left :: 4
xdg_toplevel_resize_edge_top_left :: 5
xdg_toplevel_resize_edge_bottom_left :: 6
xdg_toplevel_resize_edge_right :: 8
xdg_toplevel_resize_edge_top_right :: 9
xdg_toplevel_resize_edge_bottom_right :: 10

xdg_toplevel_state_maximized :: 1
xdg_toplevel_state_fullscreen :: 2
xdg_toplevel_state_resizing :: 3
xdg_toplevel_state_activated :: 4
xdg_toplevel_state_tiled_left :: 5
xdg_toplevel_state_tiled_right :: 6
xdg_toplevel_state_tiled_top :: 7
xdg_toplevel_state_tiled_bottom :: 8
xdg_toplevel_state_suspended :: 9
xdg_toplevel_state_constrained_left :: 10
xdg_toplevel_state_constrained_right :: 11
xdg_toplevel_state_constrained_top :: 12
xdg_toplevel_state_constrained_bottom :: 13

xdg_toplevel_wm_capabilities_window_menu :: 1
xdg_toplevel_wm_capabilities_maximize :: 2
xdg_toplevel_wm_capabilities_fullscreen :: 3
xdg_toplevel_wm_capabilities_minimize :: 4

xdg_toplevel_listener :: struct {
	configure: proc "c" (data: rawptr, self: ^xdg_toplevel, width: i32, height: i32, states: ^Array),
	close: proc "c" (data: rawptr, self: ^xdg_toplevel),
	configure_bounds: proc "c" (data: rawptr, self: ^xdg_toplevel, width: i32, height: i32),
	wm_capabilities: proc "c" (data: rawptr, self: ^xdg_toplevel, capabilities: ^Array),
}

xdg_toplevel_add_listener :: proc "contextless" (self: ^xdg_toplevel, listener: ^xdg_toplevel_listener, data: rawptr) -> c.int {
	return proxy_add_listener(cast(^Proxy)self, cast([^]rawptr)listener, data)
}

xdg_toplevel_destroy :: proc "contextless" (self: ^xdg_toplevel) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

xdg_toplevel_set_parent :: proc "contextless" (self: ^xdg_toplevel, parent: ^xdg_toplevel) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 1, nil, proxy_get_version(cast(^Proxy)self), 0, rawptr(parent))
}

xdg_toplevel_set_title :: proc "contextless" (self: ^xdg_toplevel, title: cstring) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 2, nil, proxy_get_version(cast(^Proxy)self), 0, title)
}

xdg_toplevel_set_app_id :: proc "contextless" (self: ^xdg_toplevel, app_id: cstring) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 3, nil, proxy_get_version(cast(^Proxy)self), 0, app_id)
}

xdg_toplevel_show_window_menu :: proc "contextless" (self: ^xdg_toplevel, seat: ^wl_seat, serial: u32, x: i32, y: i32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 4, nil, proxy_get_version(cast(^Proxy)self), 0, rawptr(seat), serial, x, y)
}

xdg_toplevel_move :: proc "contextless" (self: ^xdg_toplevel, seat: ^wl_seat, serial: u32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 5, nil, proxy_get_version(cast(^Proxy)self), 0, rawptr(seat), serial)
}

xdg_toplevel_resize :: proc "contextless" (self: ^xdg_toplevel, seat: ^wl_seat, serial: u32, edges: u32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 6, nil, proxy_get_version(cast(^Proxy)self), 0, rawptr(seat), serial, edges)
}

xdg_toplevel_set_max_size :: proc "contextless" (self: ^xdg_toplevel, width: i32, height: i32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 7, nil, proxy_get_version(cast(^Proxy)self), 0, width, height)
}

xdg_toplevel_set_min_size :: proc "contextless" (self: ^xdg_toplevel, width: i32, height: i32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 8, nil, proxy_get_version(cast(^Proxy)self), 0, width, height)
}

xdg_toplevel_set_maximized :: proc "contextless" (self: ^xdg_toplevel) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 9, nil, proxy_get_version(cast(^Proxy)self), 0)
}

xdg_toplevel_unset_maximized :: proc "contextless" (self: ^xdg_toplevel) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 10, nil, proxy_get_version(cast(^Proxy)self), 0)
}

xdg_toplevel_set_fullscreen :: proc "contextless" (self: ^xdg_toplevel, output: ^wl_output) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 11, nil, proxy_get_version(cast(^Proxy)self), 0, rawptr(output))
}

xdg_toplevel_unset_fullscreen :: proc "contextless" (self: ^xdg_toplevel) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 12, nil, proxy_get_version(cast(^Proxy)self), 0)
}

xdg_toplevel_set_minimized :: proc "contextless" (self: ^xdg_toplevel) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 13, nil, proxy_get_version(cast(^Proxy)self), 0)
}

// ---- xdg_popup ----

xdg_popup_error_invalid_grab :: 0

xdg_popup_listener :: struct {
	configure: proc "c" (data: rawptr, self: ^xdg_popup, x: i32, y: i32, width: i32, height: i32),
	popup_done: proc "c" (data: rawptr, self: ^xdg_popup),
	repositioned: proc "c" (data: rawptr, self: ^xdg_popup, token: u32),
}

xdg_popup_add_listener :: proc "contextless" (self: ^xdg_popup, listener: ^xdg_popup_listener, data: rawptr) -> c.int {
	return proxy_add_listener(cast(^Proxy)self, cast([^]rawptr)listener, data)
}

xdg_popup_destroy :: proc "contextless" (self: ^xdg_popup) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

xdg_popup_grab :: proc "contextless" (self: ^xdg_popup, seat: ^wl_seat, serial: u32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 1, nil, proxy_get_version(cast(^Proxy)self), 0, rawptr(seat), serial)
}

xdg_popup_reposition :: proc "contextless" (self: ^xdg_popup, positioner: ^xdg_positioner, token: u32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 2, nil, proxy_get_version(cast(^Proxy)self), 0, rawptr(positioner), token)
}

// ---- zxdg_decoration_manager_v1 ----

zxdg_decoration_manager_v1_destroy :: proc "contextless" (self: ^zxdg_decoration_manager_v1) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

zxdg_decoration_manager_v1_get_toplevel_decoration :: proc "contextless" (self: ^zxdg_decoration_manager_v1, toplevel: ^xdg_toplevel) -> ^zxdg_toplevel_decoration_v1 {
	return cast(^zxdg_toplevel_decoration_v1)proxy_marshal_flags(cast(^Proxy)self, 1, &zxdg_toplevel_decoration_v1_interface, proxy_get_version(cast(^Proxy)self), 0, rawptr(nil), rawptr(toplevel))
}

// ---- zxdg_toplevel_decoration_v1 ----

zxdg_toplevel_decoration_v1_error_unconfigured_buffer :: 0
zxdg_toplevel_decoration_v1_error_already_constructed :: 1
zxdg_toplevel_decoration_v1_error_orphaned :: 2
zxdg_toplevel_decoration_v1_error_invalid_mode :: 3

zxdg_toplevel_decoration_v1_mode_client_side :: 1
zxdg_toplevel_decoration_v1_mode_server_side :: 2

zxdg_toplevel_decoration_v1_listener :: struct {
	configure: proc "c" (data: rawptr, self: ^zxdg_toplevel_decoration_v1, mode: u32),
}

zxdg_toplevel_decoration_v1_add_listener :: proc "contextless" (self: ^zxdg_toplevel_decoration_v1, listener: ^zxdg_toplevel_decoration_v1_listener, data: rawptr) -> c.int {
	return proxy_add_listener(cast(^Proxy)self, cast([^]rawptr)listener, data)
}

zxdg_toplevel_decoration_v1_destroy :: proc "contextless" (self: ^zxdg_toplevel_decoration_v1) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

zxdg_toplevel_decoration_v1_set_mode :: proc "contextless" (self: ^zxdg_toplevel_decoration_v1, mode: u32) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 1, nil, proxy_get_version(cast(^Proxy)self), 0, mode)
}

zxdg_toplevel_decoration_v1_unset_mode :: proc "contextless" (self: ^zxdg_toplevel_decoration_v1) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 2, nil, proxy_get_version(cast(^Proxy)self), 0)
}

// ---- ext_background_effect_manager_v1 ----

ext_background_effect_manager_v1_error_background_effect_exists :: 0

ext_background_effect_manager_v1_capability_blur :: 1

ext_background_effect_manager_v1_listener :: struct {
	capabilities: proc "c" (data: rawptr, self: ^ext_background_effect_manager_v1, flags: u32),
}

ext_background_effect_manager_v1_add_listener :: proc "contextless" (self: ^ext_background_effect_manager_v1, listener: ^ext_background_effect_manager_v1_listener, data: rawptr) -> c.int {
	return proxy_add_listener(cast(^Proxy)self, cast([^]rawptr)listener, data)
}

ext_background_effect_manager_v1_destroy :: proc "contextless" (self: ^ext_background_effect_manager_v1) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

ext_background_effect_manager_v1_get_background_effect :: proc "contextless" (self: ^ext_background_effect_manager_v1, surface: ^wl_surface) -> ^ext_background_effect_surface_v1 {
	return cast(^ext_background_effect_surface_v1)proxy_marshal_flags(cast(^Proxy)self, 1, &ext_background_effect_surface_v1_interface, proxy_get_version(cast(^Proxy)self), 0, rawptr(nil), rawptr(surface))
}

// ---- ext_background_effect_surface_v1 ----

ext_background_effect_surface_v1_error_surface_destroyed :: 0

ext_background_effect_surface_v1_destroy :: proc "contextless" (self: ^ext_background_effect_surface_v1) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 0, nil, proxy_get_version(cast(^Proxy)self), MARSHAL_FLAG_DESTROY)
}

ext_background_effect_surface_v1_set_blur_region :: proc "contextless" (self: ^ext_background_effect_surface_v1, region: ^wl_region) {
	_ = proxy_marshal_flags(cast(^Proxy)self, 1, nil, proxy_get_version(cast(^Proxy)self), 0, rawptr(region))
}

