#!/usr/bin/env python3
"""Generate Odin bindings for Wayland protocols from their XML descriptions.

Emits the wl_interface/wl_message dispatch tables that libwayland-client needs,
plus typed request wrappers and listener structs. Equivalent to what
wayland-scanner produces for C, but in Odin, so the repo needs no C step.
"""
import sys, xml.etree.ElementTree as ET

TYPE_CHAR = {
    "int": "i", "uint": "u", "fixed": "f", "string": "s",
    "object": "o", "new_id": "n", "array": "a", "fd": "h",
}
ODIN_TYPE = {
    "int": "i32", "uint": "u32", "fixed": "Fixed", "string": "cstring",
    "array": "^Array", "fd": "i32",
}
KEYWORDS = {"context", "in", "map", "matrix", "using", "when", "where", "size"}


def ident(name):
    return name + "_" if name in KEYWORDS else name


def signature(msg):
    sig = ""
    since = msg.get("since")
    if since and int(since) > 1:
        sig += since
    for arg in msg.findall("arg"):
        t = arg.get("type")
        if arg.get("allow-null") == "true" and t in ("object", "string", "array", "new_id"):
            sig += "?"
        if t == "new_id" and arg.get("interface") is None:
            # An untyped new_id is sent as interface name, version, then the id.
            sig += "sun"
        else:
            sig += TYPE_CHAR[t]
    return sig


def arg_types(msg):
    """The wl_interface pointer slot for each argument (nil when untyped)."""
    out = []
    for arg in msg.findall("arg"):
        t = arg.get("type")
        iface = arg.get("interface")
        if t in ("object", "new_id") and iface:
            out.append("&" + iface + "_interface")
        elif t == "new_id":
            # An untyped new_id (wl_registry.bind) marshals as three slots.
            out += ["nil", "nil", "nil"]
        else:
            out.append("nil")
    return out


def odin_arg(arg):
    t = arg.get("type")
    if t in ODIN_TYPE:
        return ODIN_TYPE[t]
    if t == "object":
        return "^" + arg.get("interface") if arg.get("interface") else "rawptr"
    if t == "new_id":
        return "^" + arg.get("interface") if arg.get("interface") else "rawptr"
    raise SystemExit("unhandled arg type " + t)


def gen(paths, out):
    w = out.write
    w("// Code generated by tools/wl_gen.py. DO NOT EDIT.\n")
    w("//\n// Sources:\n")
    for p in paths:
        w("//   %s\n" % p)
    w("package wayland\n\nimport \"core:c\"\n\n")

    interfaces = []
    for path in paths:
        root = ET.parse(path).getroot()
        for iface in root.findall("interface"):
            interfaces.append(iface)

    # Opaque proxy types, one per interface.
    for iface in interfaces:
        w("%s :: struct {}\n" % iface.get("name"))
    w("\n")

    # Interface descriptor globals, populated by the init proc below.
    for iface in interfaces:
        w("%s_interface: Interface\n" % iface.get("name"))
    w("\n")

    body = []
    for iface in interfaces:
        name = iface.get("name")
        reqs = iface.findall("request")
        evts = iface.findall("event")

        for kind, msgs in (("requests", reqs), ("events", evts)):
            if not msgs:
                continue
            w("@(private) %s_%s: [%d]Message\n" % (name, kind, len(msgs)))
            for i, m in enumerate(msgs):
                types = arg_types(m)
                if types:
                    w("@(private) %s_%s_types_%d := [%d]^Interface{%s}\n"
                      % (name, kind, i, len(types), ", ".join(types)))
            for i, m in enumerate(msgs):
                types = arg_types(m)
                ptr = ("&%s_%s_types_%d[0]" % (name, kind, i)) if types else "nil"
                body.append("\t%s_%s[%d] = {%s, %s, %s}"
                            % (name, kind, i, odin_str(m.get("name")), odin_str(signature(m)), ptr))
        body.append("\t%s_interface = {%s, %s, %d, %s, %d, %s}" % (
            name, odin_str(name), iface.get("version"),
            len(reqs), ("&%s_requests[0]" % name) if reqs else "nil",
            len(evts), ("&%s_events[0]" % name) if evts else "nil",
        ))
    w("\n")

    w('@(init, private)\ninit_interfaces :: proc "contextless" () {\n')
    w("\n".join(body))
    w("\n}\n\n")

    for iface in interfaces:
        gen_interface(w, iface)


def odin_str(s):
    return '"%s"' % s


def gen_interface(w, iface):
    name = iface.get("name")
    w("// ---- %s ----\n\n" % name)

    for enum in iface.findall("enum"):
        for entry in enum.findall("entry"):
            w("%s_%s_%s :: %s\n" % (name, enum.get("name"), ident(entry.get("name")),
                                    entry.get("value")))
        if enum.findall("entry"):
            w("\n")

    evts = iface.findall("event")
    if evts:
        w("%s_listener :: struct {\n" % name)
        for e in evts:
            args = ["data: rawptr", "self: ^%s" % name]
            for a in e.findall("arg"):
                args.append("%s: %s" % (ident(a.get("name")), odin_arg(a)))
            w("\t%s: proc \"c\" (%s),\n" % (ident(e.get("name")), ", ".join(args)))
        w("}\n\n")
        w("%s_add_listener :: proc \"contextless\" (self: ^%s, listener: ^%s_listener, data: rawptr) -> c.int {\n"
          % (name, name, name))
        w("\treturn proxy_add_listener(cast(^Proxy)self, cast([^]rawptr)listener, data)\n}\n\n")

    for opcode, req in enumerate(iface.findall("request")):
        gen_request(w, name, opcode, req)

    if not any(r.get("type") == "destructor" for r in iface.findall("request")) and name != "wl_display":
        w("%s_destroy :: proc \"contextless\" (self: ^%s) {\n\tproxy_destroy(cast(^Proxy)self)\n}\n\n" % (name, name))


def gen_request(w, iface_name, opcode, req):
    rname = req.get("name")
    fn = "%s_%s" % (iface_name, rname)
    destructor = req.get("type") == "destructor"

    args = req.findall("arg")
    new_ids = [a for a in args if a.get("type") == "new_id"]
    ret = new_ids[0] if new_ids else None
    untyped_new_id = ret is not None and ret.get("interface") is None

    params = ["self: ^%s" % iface_name]
    for a in args:
        if a.get("type") == "new_id":
            if untyped_new_id:
                params.append("interface: ^Interface")
                params.append("version: u32")
            continue
        params.append("%s: %s" % (ident(a.get("name")), odin_arg(a)))

    if ret is None:
        ret_type = ""
    elif untyped_new_id:
        ret_type = " -> rawptr"
    else:
        ret_type = " -> ^%s" % ret.get("interface")

    w("%s :: proc \"contextless\" (%s)%s {\n" % (fn, ", ".join(params), ret_type))

    if ret is None:
        iface_arg, version_arg = "nil", "proxy_get_version(cast(^Proxy)self)"
    elif untyped_new_id:
        iface_arg, version_arg = "interface", "version"
    else:
        iface_arg = "&%s_interface" % ret.get("interface")
        version_arg = "proxy_get_version(cast(^Proxy)self)"

    call = []
    for a in args:
        t = a.get("type")
        if t == "new_id":
            if untyped_new_id:
                call += ["interface.name", "version", "rawptr(nil)"]
            else:
                call.append("rawptr(nil)")
        elif t == "object":
            call.append("rawptr(%s)" % ident(a.get("name")))
        elif t == "array":
            call.append("rawptr(%s)" % ident(a.get("name")))
        else:
            call.append(ident(a.get("name")))

    flags = "MARSHAL_FLAG_DESTROY" if destructor else "0"
    varargs = ("".join(", " + c for c in call))
    marshal = ("proxy_marshal_flags(cast(^Proxy)self, %d, %s, %s, %s%s)"
               % (opcode, iface_arg, version_arg, flags, varargs))

    if ret is None:
        w("\t_ = %s\n" % marshal)
    elif untyped_new_id:
        w("\treturn rawptr(%s)\n" % marshal)
    else:
        w("\treturn cast(^%s)%s\n" % (ret.get("interface"), marshal))
    w("}\n\n")


if __name__ == "__main__":
    with open(sys.argv[1], "w") as f:
        gen(sys.argv[2:], f)
